act-now-coalition/covid-data-model

- .github/workflows/staging.yml
- .gitignore
- libs/DeployDataset.py
This helps automate the serving of datasets, on a regular basis using a scheduled (hourly) lambda function to make a dataset for the DoD.
This is only configured to work on staging atm.
After an hour has passed post-deployment, the new dataset will be available publically at https://covidactnow-models-staging.s3.amazonaws.com/my-key
> Automate Deploying Dataset

- libs/CovidDatasets.py
- libs/build_params.py
- run.py
- validate.py
`validate.py` wraps a run of `run.py`, validating that `run.py` does not crash and produces the expected number of non-empty result files. 
Will need to be updated as support for additional territories are added (Guam, American Samoa, Northern Mariana Islands)
> Add a sanity check for runs of run.py

- run.py
- validate.py
Fix validate to only clear the result dir if it exists, fix run.py to create the result dir if it does not exist
Fixes #47
> Fix errors from 'result/test' being missing.

- SETUP.md
- libs/CovidDatasets.py
- requirements.txt
As discussed, do a full clone for caching `covid-data-public` and call `git lfs fetch` on the repo.
Does not yet support git urls to clone a specific hash.
My intention is to merge this into master, then pull master into the dod branch.
> Switch to full clone for caching data, also fetch lfs objects

- run.py
Bench on 8 core 64GB ram MBP:
For states, it goes from 
```
python run.py  65.40s user 4.59s system 1058% cpu 6.615 total
```
to 
```
python run.py  34.95s user 1.11s system 101% cpu 35.607 total
```
For counties, from >20 min to
```
python run.py  1915.95s user 163.88s system 1306% cpu 2:39.23 total
```
> Add Basic Multiprocessing

- libs/datasets/beds.py
- libs/datasets/timeseries.py
- requirements.txt
- run.py
- run_model.py
This adds a more direct cli - couple advantages:
1. Can choose if you want to run the county or state model.
2. Can pass `--deploy` flag which will save files to the public data directory in `covid-projections`
3. You can choose a specific state to run on
example:
```
./run_model.py state --deploy
```
> Add easier cli for model

- libs/datasets/dataset_utils.py
- run.py
Uses a `contextmanager` to set the local copy of covid-data-public to the specified hash, if one is supplied. Resets to the existing branch on exit, and errors if the working tree is not clean.
Currently only supported for `run.py`, but if there's interest I could wire it into other entry points as well.
> Add support for a COVID_PUBLIC_DATA_HASH env variable

- .gitignore
- libs/datasets/data_version.py
- libs/datasets/dataset_utils.py
- run.py
- run_model.py
Also output a version file when the model is run. Git hash support is in the form of the `--git-hash` commandline argument, as that seems to be how we are configuring these runs.
> Add git hash support to run_model.py

- run.py
- run_model.py
Small changes:
* removes the logic that "archives" the existing directories by renaming outputs.  It caused more confusion that intended.
* fixes the output dir for state to point at the output directory passed in rather than the constant.
* using the implicit false (recommendation per [gsg](https://google.github.io/styleguide/pyguide.html#214-truefalse-evaluations))
> Small fixes to run.py - removing archiving folder

- run.py
Doesn't yet address the actual error in https://github.com/covid-projections/covid-projections/issues/419, but this adds error logging that would've helped catch it sooner.
> Adding error logging to catch errors from parallel calls

- libs/datasets/dataset_utils.py
- libs/datasets/sources/fips_population.py
- libs/datasets/sources/jhu_dataset.py
- libs/datasets/timeseries.py
- libs/enums.py
- run.py
Okay - so found an annoying bug in the fips data. Basically there are duplicate rows for some counties.
here's an example, notice on 4/23 how there are two different rows for that fips: 
Also fixes a bug on the county replacement to make sure that counties aren't adding additional unknown data by joining on more than fips.
I would like to figure out a way to standardize this missing data.  this is a quick fix, but I think there's a larger ticket that needs to be done so that we're not handling this differently for every case.
> Fixing fips aggregation

- libs/datasets/data_version.py
- libs/datasets/sources/dh_beds.py
- libs/datasets/sources/fips_population.py
For better or for worse, the DH beds data was broken because we check for duplicate indexes and the PR bed data wasn't being processed properly.
This fixes that. 
Also, drops all Virgin islands data as we have no fips or population data on it right now.
> Fixing PR processing for beds data

- README.md
- deploy.sh
- deploy_dod_dataset.py
- libs/build_dod_dataset.py
- libs/build_params.py
- run.py
- run_data.py
- run_model.py
Changing the deploy directory wasn't quite working properly, so this standardizes a bit of that.
Also, added a `deploy.sh` file to illustrate how to deploy the data to the website.  It doesn't quite cover #123 , but I think it's a start and at least documents the current process.
I named it `deploy.sh` rather than `run.sh` because it's pretty specific to what you need to do to actually deploy to the website, rather than just run the models for testing
> Fix deploy subdirectory

- libs/datasets/dataset_utils.py
This restores the capability of using COVID_DATA_PUBLIC env var to specify where to find that repo.  
I'm not opposed to changing the way this works (e.g. using CLI arguments), but if/when we do, we should add a legacy check for COVID_DATA_PUBLIC and tell people to use the command-line arg instead.
> Enable COVID_DATA_PUBLIC env var again.

- libs/datasets/__init__.py
- libs/datasets/custom_aggregations.py
- libs/datasets/sources/covid_tracking_source.py
- libs/datasets/timeseries.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/139
Adds hospitalization data source from the covid tracking data and adds code to convert it to a timeseries.
```python
covid_tracking_source = CovidTrackingDataSource.local()
timeseries = covid_tracking_source.timeseries()
```
I would like to add a merge function on the timeseries dataset that allows us to combine two timeseries datasets, but don't have time right now.
There is no external schema that this affects right now.
> Adding Covid Tracking hospitalization numbers Data Source

- deploy_dod_dataset.py
- libs/dataset_deployer.py
More work on 145 https://github.com/covid-projections/covid-data-model/issues/145
Moves logic out of deploy_dod_dataset + adds a helper function to deploy all shapefiles
> moving datset deployer out of deploy_dod_dataset

- .github/workflows/deploy_api.yml
* Runs run.sh and publishes the results to data.covidactnow.org/snapshot/<run-id>
* Scheduled for 12:30 daily, which should be after the relevant covid-data-public
update.
@fridiculous Before we merge this we need to add the AWS secrets for the data bucket to github (as AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY).  Can you do that?
> Add deploy-api Github Action workflow.

- libs/pipelines/can_model_pipeline.py
- run_model.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/145
This just moves the functionality to run the normal model into the pipelines folder.
To be clear, nothing is actually running from run.py directly, it's only accessed from `./run_model.py`.
I'd like to improve the cli structure so that we'll have an entry point for the existing run_model.py and run_data.py files. By moving this to a pipeline, i can make a new run.py to be an actual entry point.
> Move run py to pipelines

- cli/run_data.py
- cli/run_dod_dataset.py
- cli/run_model.py
- deploy_dod.sh
- deploy_website.sh
- run.py
- run.sh
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/145
Okay - a bit larger change.
This just hooks in all of the various command lines into one master cli so it's easier to get around and gives a common home for all cli functionality. 
I didn't do any restructuring right now, just wanted to keep the current structure as closely as possible.
I'm running all of the deploy scripts right now to verify that everything hooks together.
```
(covid-data-model) ➜  covid-data-model git:(move-to-common-cli) ✗ ./run.py
Usage: run.py [OPTIONS] COMMAND [ARGS]...
Entry point for covid-data-model CLI.
Options:
--help  Show this message and exit.
Commands:
data        Generate reports from raw data.
deploy-dod  Generates and runs dod data projections from model outputs. …
```
> Move to common cli

- .github/workflows/python_unit_tests.yml
- libs/datasets/dataset_utils.py
- libs/datasets/sources/dh_beds.py
- test/beds_dataset_test.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/201
It also pulls down the covid-data-public repo so that we can write tests on the actual data sources we have.  I think in the ideal world I would rather have smaller unit test coverage, but this will at least give us an opportunity to make sure PRs aren't breaking existing behavior.
> Fixing duplicate county data in beds

- .github/workflows/label_api_snapshot.yml
- README.md
- tools/label-api.sh
- tools/publish-api.sh
- tools/push-api.sh
Add Github Action Workflow for labeling snapshots.
* Triggers off of a repository dispatch with event type 'label-api-snapshot'.
* Requires 'label' and 'snapshot_id' in the payload.
* For now just copies the files, but we'd like a symlink or similar in the future.
Also added `tools/publish-api.sh` and `tools/label-api.sh` helpers for invoking
workflows manually, and added to README.md.
This PR helps address issue #126.
> Add workflow for labelling snapshots and tools/label-api.sh helper for invoking.

- run.sh
https://github.com/covid-projections/covid-data-model/commit/575fa632455d5720af18cc1c675340e3b49805e4 refactored some paths and inadvertantly started using API_OUTPUT_STATES and API_OUTPUT_COUNTIES in places where we need to use the "legacy" state / county directories (`/` and `/county/` respectively).
> Fix #235.  Paths got messed up in run.sh.

- run.sh
https://github.com/covid-projections/covid-data-model/actions/runs/80995224 failed with:
> Generating pyseir_state_summaries.zip from output/pyseir/state_summaries.
> ./covid-data-model/run.sh: line 128: pushd: output/pyseir: No such file or directory
I suspect this will fix it (though it's untested).
> Generate pyseir_state_summaries.zip as part of execute_model

- .github/workflows/deploy_api.yml
- README.md
- requirements.txt
- run.py
We need to add SENTRY_DSN into the github secrets, but this will add exception logging to slack so that we can more easily start seeing errors! 
> Add sentry and a basic catch all exception tracker

- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/inference/fit_results.py
This PR addresses 2 issues
1. incorrect county R_t shipping. Previously, state lookup codes were being used incorrectly resulting in the "first" county's R_t being used for subsequent fips in a state.
2. Whitelist filtering was previously being checked after also checking for valid fit results, which if not existing, went down an alternate code path.
Acceptance tests performed:
- Verified that correct county R_t are being shipped and differ across the state.
- Verified that the number of output/web_ui/county/*.2.json == 291 == whitelist length == number of MLE reports.
> Update fit_results lookup by fips

- .github/workflows/deploy_api.yml
I mostly just wanted a single place where I can update the covid-data-model
branch that's being run against (I almost messed this up when trying to do a
test yesterday). But I took the opportunity to unify all the env vars that are
used repeatedly and/or are important enough to be top-level constants.
> Unify env vars in deploy workflow.

- cli/run_counties_api.py
- libs/datasets/results_schema.py
- libs/pipelines/api_pipeline.py
- libs/pipelines/dod_pipeline.py
- libs/pipelines/top_counties_pipeline.py
- libs/validate_results.py
This enables generating OBSERVED_INTERVENTION files in the API for inference projections.
This required tweaking our validation in several places, since we expect many
counties not to have inference results.
This PR addresses issue #258.
- [n/a] Are the [JSON schemas](https://github.com/covid-projections/covid-data-model/tree/master/api/schemas) updated?
- [n/a] Are the [api docs](https://github.com/covid-projections/covid-data-model/blob/master/api/README.V1.md) updated?
> Fix #258: Support Inference Output for counties

- api/can_api_definition.py
- api/schemas/CANPredictionTimeseriesRow.json
- api/schemas/CovidActNowCountiesTimeseries.json
- api/schemas/CovidActNowStatesTimeseries.json
- libs/datasets/can_model_output_schema.py
- libs/datasets/results_schema.py
- libs/functions/calculate_projections.py
- libs/functions/generate_api.py
- libs/functions/get_can_projection.py
- libs/pipelines/api_pipeline.py
Adds ICU/Vent capacity/utilization numbers to state and county timeseries.
Also fixes a bug i introduced where it was pulling incorrect values for cumulative testing data + add a validation to make sure it never happens again.
> Add icu ventilator usage + fix cumulative tests

- api/can_api_definition.py
- api/schemas/CANPredictionTimeseriesRow.json
- api/schemas/CovidActNowCountiesTimeseries.json
- api/schemas/CovidActNowStatesTimeseries.json
- libs/datasets/can_model_output_schema.py
- libs/functions/generate_api.py
> Expose inferred and "indicator" historical Rt values through the API timeseries

- pyseir/cli.py
This should be merged after the PR that adjusts the website to accommodate: https://github.com/covid-projections/covid-projections/pull/595
> Default output-interval-days to 1 in model.

- pyseir/deployment/webui_data_adaptor_v1.py
Some edge counties do not contain a composite R_t measure. This fills NaNs in those cases.
> R_t Add KeyError handling

- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/models/suppression_policies.py
After parameter updates, this backfill parameter has not been updated, but impacts those locations which do not have hospitalization data.
> Fix hospitalization rate in webui output

- libs/datasets/sources/covid_care_map.py
Don't have to merge this, but wanted to leave in the option. 
Basically it uses the current non-covid occupancy as the default value for nevada (just statically pulling).
This may be a bit low (since typical occupancy is higher), but this gives the current value and would product occupancy values closer to the actuals.
> Overriding nv occupancy with actual non-covid icu utilization from 4/28 NHA data

- pyseir/inference/infer_rt.py
This PR adds a time-lag alignment feature when computing R_t, which brings down our previous estimate of R_t down by a bit for some states, and quite a lot for others where death was a significantly lagging indicator relative to cases). Likely this means that cases in some localities are being processed and reported much more efficiently. 
The alignment procedure finds the time shift that maximizes correlation of the time series curvature, i.e. we fit the shape of the curve.
> Align rt values

- pyseir/inference/infer_rt.py
- pyseir/inference/model_fitter.py
- pyseir/inference/whitelist_generator.py
Make the whitelist a little more conservative from now, going from 20 case low threshold to 50 case, which is 50% of counties -> 25% of counties due to the steep recall curve.  We can try to push this back down in a few days when we move to R_t suppression models.
Also some minor fit tweaks and plotting bug fix.
> Make whitelist slightly more stringent and tweak fitter.

- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/load_data.py
- pyseir/parameters/parameter_ensemble_generator.py
Add in ICU data and rescaling. Update hosp acute LOS to reduce the occupancy ratio for ICU / total.  The results below show how we improve the absolute tuning, but the variation in ICU / general occupancy is also reduced to zero for states where this is available.
These plots are for CA only.
Before. Hosp general too low, ICUs look right in absolute terms.
--------
After. Hosp and ICUs look right in absolute and relative terms.
---------
> Add ICU Normalization + Param Update.

- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/inference/infer_rt.py
- pyseir/load_data.py
This PR addresses issues with AR and HI reporting erroneously 0 ICU hosps. (HI may not be an error), but AR certainly is.  This removes grounding to zero. 
For R_t inference, we also bound the backward shift to 3 weeks instead of 4 to prevent some spurious fits back to old data.
> Remove bad data states

- api/can_api_definition.py
- libs/datasets/combined_datasets.py
- libs/datasets/dataset_export.py
- libs/functions/generate_api.py
- pyseir/load_data.py
- pyseir/parameters/parameter_ensemble_generator.py
We moved the logic for where NV beds from covid tracking to the combined dataset.  use that for hospitalization numbers. 
Without this fix pyseir was not picking up the NV bed overrides
> make pyseir load from combined datasets rather than pulling in covid tracking

- libs/datasets/sources/nha_hospitalization.py
Not needed after https://github.com/covid-projections/covid-data-public/pull/40 is merged
Part of https://trello.com/c/oGNg8jGK/17-update-icu-hospital-data-from-daily-nevada-emails
> rm skiprows in NevadaHospitalAssociationData

- test/dataset_utils_test.py
Part of 
https://trello.com/c/oGNg8jGK/17-update-icu-hospital-data-from-daily-nevada-emails
involves changing how timeseries data that appear in multiple sources get combined. I want a test for the existing behavior before changing the implementation.
Adds tests exercising basic functionality of  `dataset_utils_test.fill_fields_with_data_source`
> Add fill_fields_with_data_source test ahead of changing the implementation

- pyseir/inference/infer_rt.py
In this PR I updated the gaussian smoothing used to calculate Rt so that it begins counting from the first non-zero entry. Previously is started with the last non-zero entry, which would then exclude meaningful data for calculating Rt.
- [ irrelevant] Are the [JSON schemas](https://github.com/covid-projections/covid-data-model/tree/master/api/schemas) updated?
- [ irrelevant] Are the [api docs](https://github.com/covid-projections/covid-data-model/blob/master/api/README.V1.md) updated?
- [ we'll see!] Are tests passing?
> fix inferred rt calculation

- api/can_api_definition.py
- api/schemas/CovidActNowAreaSummary.json
- api/schemas/CovidActNowCountiesAPI.json
- api/schemas/CovidActNowCountiesSummary.json
- api/schemas/CovidActNowCountiesTimeseries.json
- api/schemas/CovidActNowStatesAPI.json
- api/schemas/CovidActNowStatesSummary.json
- api/schemas/CovidActNowStatesTimeseries.json
- libs/datasets/combined_datasets.py
- libs/datasets/common_fields.py
- libs/datasets/sources/test_and_trace.py
- libs/datasets/timeseries.py
- libs/functions/generate_api.py
See https://trello.com/c/eYwZ8roa/108-add-number-of-tracers-employed-to-our-api and 
https://covidactnow.slack.com/archives/C0110QQAPJA/p1589227207223300
> Add TestAndTrace to api output

- libs/datasets/common_fields.py
as found in api/can_api_definition.py and libs/datasets/can_model_output_schema.py
Follow up to https://github.com/covid-projections/covid-data-public/pull/52/
> add VENTILATOR_CAPACITY to common_fields

- libs/datasets/combined_datasets.py
- libs/datasets/dataset_cache.py
- pyseir/cli.py
- run.py
- test/conftest.py
- test/dataset_cache_test.py
Alrighty, so i found out that one of the main reasons the modeling code is very slow now is that it's reloading the combined datasets multiple times. 
We attempt to get around this with the lru_cache decorator, but it seems that the `lru_cache` does not cache across processes (which makes sense). So, as a result, it's reloading the combined datasets a lot of times.  This is a very slow operation which is not really intended to be done more than once. 
So, I added in a decorator that caches these datasets on disk which greatly speeds up the operations.  I don't really love this approach in general - I would much rather refactor the pyseir code to load the required data frames once and figure out the best way to pass that data through - but that requires a lot more refactoring and more time …
> Adding cache dir to combined datasets

- pyseir/deployment/webui_data_adaptor_v1.py
The following warning looks likely to catch the problems behind
https://trello.com/c/oFdotko9/132-track-down-why-we-are-not-showing-data-for-counties-that-have-over-50-cases
> add warning when clearing Rt

- libs/build_processed_dataset.py
- libs/datasets/dataset_utils.py
- libs/datasets/sources/cds_dataset.py
- libs/datasets/sources/covid_tracking_source.py
- libs/datasets/timeseries.py
- libs/pipelines/api_pipeline.py
- test/build_processed_data_test.py
- test/combined_dataset_test.py
https://trello.com/c/tQj1yUjh/145-cds-data-source-missing-proper-county-level-data
https://github.com/covid-projections/covid-data-model/pull/438 added tests.
Changes build_processed_data to get COVID negative/positive test data from combined_datasets instead of directly from the data source classes. It mostly transforms the columns back to their original form to reduce the chance of accidentally breaking code that depends on the current return value.
> build_processed_data gets test data from combined_datasets

- pytest.ini
- requirements.txt
- requirements_test.txt
- run.py
This PR fixes some lint warnings introduced recently and fixes version conflicts in the requirements files.
> clean lint and upgrade pytest

- libs/datasets/dataset_cache.py
- pyseir/cli.py
- run.py
- run.sh
- test/conftest.py
Made a few improvements to the dataset cache after getting to use it some more:
- Set the default directory to be `pyseir_data` (where we load other intermediate cached data) - this replaces the tmpdir meaning that users won't have to have the environment variable set to get the effects of the cache on multiple runs.  If people are doing work locally it will be much faster.
- Load the result of the function call instead of reading it from disk every time. I noticed in profiling a lot of the time was spent reading from disk.
- Increase the time to one hour before reloading - reduces the number of times that the cache has to be reloaded
- Added some more clear logging to make it easier to understand if the combined dataset results are being loaded from a cache or not
> Improve Dataset Caching

- requirements.txt
Thought I'd bring up a quick package managing question (everyone's favorite thing).
I added the newer version of jupyter (jupyterlab) to requirements.
If it was a heavier lift I'd say that all the debug tools like jupyter/jupyterlab don't need to be in the remote build, but I don't think it's too bad atm.
Also, @ghop02 did we get burned sometime in the past and decided to pin everything? I don't particularly want to sign up for us using poetry or pipenv. Just curious.
- [YES] Are tests passing?
> Added Jupyter Lab to Requirements.txt

- .github/workflows/deploy_api.yml
- .github/workflows/python_unit_tests.yml
- libs/datasets/sources/covid_tracking_source.py
- test/combined_dataset_test.py
See https://trello.com/c/1HA3Egdm/189-adding-jupyterlab-appears-to-break-build-all-at-the-moment and https://covidactnow.slack.com/archives/C0110QQAPJA/p1591105732043200
> use covid tracking date column, revert data pins

- libs/datasets/sources/kinsa.py
This PR adds a datasource for kinsa data. Data is being loaded directly via the API to avoid any issues that could come from snapshotting it in covid-data-public.
> Adds kinsa datasource.

- notebooks/data_loading/kinsa_api_rt_comparison.ipynb
This PR contains a few improvements to the kinsa investigation notebook: 
* deduplicates graphs across states 
* standardizes on atypical_ili across the board
* adds plots of atypical_ili against daily cases (not smoothed)
* preliminary time lag analysis with rt values.
> Updates kinsa notebook with better visualizations, timelag analysis.

- libs/datasets/sources/cmdc.py
* add CmdcDataSource COMMON_FIELD_MAP.CommonFields.CURRENT_HOSPITALIZED
Depends on https://github.com/covid-projections/covid-data-public/pull/57 for tests to pass
> Sync field name in CmdcDataSource with Cmdc in covid-public-data repo

- libs/datasets/combined_datasets.py
- pyseir/inference/model_fitter.py
t0 guess should be in middle of range so Minuit can find a stable fit.
> update t0 guess to 30

- pyseir/ensembles/ensemble_runner.py
- pyseir/models/suppression_policies.py
This PR addresses stability in our hospitalization forecasts. The no intervention value is currently drawn from the daily pyseir model's first stage fit R value. This model is almost always higher than the 2.5 estimate provided by the CDC for scenario planning (https://www.cdc.gov/coronavirus/2019-ncov/hcp/planning-scenarios.html). Our visualization currently goes out 3 months forward. Small changes in fitter R0 cause large changes in the worst case scenario line. We believe those small changes in R0 are in the noise, especially for a forecast that assumes that we go 3 months without change. Therefore, we cap those values at a minimum of either 2.5 or fit R0.
> For Future Projections, Cap All Scenarios at R=2.5

- libs/qa/metrics.py
> fix for timedelta + remove noisy metric

- pyseir/inference/model_fitter.py
This PR removes the epsilon posterior updating after the fit that was previously applied. Now we trust the fit to find the best epsilon fit values. 
- [ running] Are tests passing?
> Disable post-fit eps posterior updating

- README.md
- SETUP.md
- cli/utils.py
- libs/pipelines/api_pipeline.py
- requirements.txt
* depends on https://github.com/covid-projections/covid-data-public/pull/62
* adds ../covid-data-public to requirements
* adds a tool that dumps the combined datasets to disk
I ran `python run.py utils save-combined-csv` and looked at `combined-tgb-save-combined-de01959-20200612T134549.csv`. Also `python run.py utils save-combined-csv --help` looks reasonable:
```
Usage: run.py utils save-combined-csv [OPTIONS]
Save the combined datasets DataFrame, cleaned up for easier comparisons.
Options:
--csv-path-format TEXT  Filename template where CSV is written  [default:
combined-{git_branch}-{git_sha}-{timestamp}.csv]
-o, --output-dir PATH
--help                  Show this message and exit.
```
> Install covidactnow.datapublic, add save-combined-csv

- pyseir/models/seir_model.py
Old Charts had ICU and General Bed capacity labels flipped 
- [ better] Are tests passing?
> fix ICU/General Bed capacity label in charts

- .github/workflows/deploy_api.yml
- libs/datasets/dataset_utils.py
- libs/datasets/sources/cds_dataset.py
- pyseir/deployment/model_to_observed_shim.py
- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/inference/infer_rt.py
- pyseir/load_data.py
This code shims the cumulative deaths timeseries in the API so that the cumulative deaths from the model agrees with the cumulative deaths from outside observed sources.
This PR addresses issue https://trello.com/c/ZDNt3or6/247-shim-model-cumulative-deaths-to-observed.
> Apply Shim to Cumulative Death s.t. Latest Observed Equals Latest Model

- libs/datasets/data_source.py
- libs/datasets/latest_values_dataset.py
- libs/datasets/sources/cmdc.py
- libs/datasets/timeseries.py
The bug with CMDC data is that they report county data as they receive it, but state data is not reported until they receive a complete days worth of data. We were aggregating any missing state rows, so for an incomplete day we were rolling up aggregates, which would return a zero or incomplete data as the latest value for a state.  
Addresses https://trello.com/c/ib7jY6Fx/236-combined-dataset-timeseries-has-incorrect-rows-for-latest-day
> Adding flag to fill specify whether or not to fill state level data by data source

- libs/build_processed_dataset.py
- pyseir/cli.py
- pyseir/inference/infer_rt.py
- run.py
https://trello.com/c/dQDAHHIH/239-ensure-loginfo-doesnt-log-to-sentry
* replace run and cli logging init with calls to common_init.configure_logging
* replace most direct use of sentry_sdk with calls to stdlib logging.
> Move run.py and cli.py to common_init.configure_logging

- .github/workflows/deploy_api.yml
Enforce a queue to the GitHub self-hosted runner that treats the creation of the entire snapshot as the job.
The previous version separated the workflow into multiple "jobs" that were linearly dependent on each other. That "jobs" abstraction is built to allow parallel processes, and if we used the GitHub hosted version it would run up to 20 jobs in parallel. However, the runner built for self-hosting prioritizes the jobs across snapshots in a way that delays the time to first snapshot completion (without changing the time to last snapshot completion). Instead of completing all the jobs of the first snapshot, it will cycle through each outstanding snapshot request calling the next available job for that snapshot.
It is better to have the early snapshot complete and unblock the person …
> GitHub Self-Hosted Runner Queue

- .github/workflows/deploy_api.yml
- libs/datasets/sources/nytimes_dataset.py
- pyseir/cli.py
- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/inference/fit_results.py
- pyseir/inference/infer_rt.py
- pyseir/load_data.py
- pyseir/utils.py
- test/pyseir/infer_rt_test.py
- test/test_pyseir_end_to_end_test.py
This PR addresses a handful of small pyseir bugs/warnings:
* Adds an option to `pyseir build-all` to run on a single fips. This further filters the counties that it runs on.
* Fixes (this)[https://sentry.io/organizations/covidactnow/issues/1748441676/] sentry error where infer rt was failing if an outlier was detected on the last day
* Fixes (this)[https://sentry.io/organizations/covidactnow/issues/1736478765/] sentry error where if there were no timeseries for a county it would error out.
* Fixes noisy logs in webui data adapter if a county didn't have a valid rt inference - before it was trying to load a non existing file, now it checks if path exists before reading into pandas data frame.
* Removed hampel filtering in load data (duplicating Natasha's change)
Some of the larger diffs …
> Fix key error exception handling

- libs/datasets/combined_datasets.py
- test/combined_dataset_test.py
Fixes https://trello.com/c/ROauACzW/270-pyseir-load-data-not-returning-latest-day
> Fixing padded nans stripping off one too many days

- libs/qa/common_df_diff.py
- test/common_df_diff_test.py
* handle ts that are all zero
* drop duplicates correctly, fixing bug where duplicate values are dropped, ignoring the index
* compare between valid values instead of min and max values.
> fix some csv-diff bugs

- libs/datasets/sources/dh_beds.py
- libs/datasets/sources/fips_population.py
- libs/datasets/sources/jhu_dataset.py
- libs/datasets/sources/nytimes_dataset.py
- libs/us_state_abbrev.py
- test/us_state_abbrev_test.py
This PR reduces the use of FIPS 99999 by datasources, which is a step towards a world where we use only the FIPS as the region identifier.
Tested by comparing the combined latest data from master and this branch. I saw that the state aggregation values didn't change, ( 'cases', '99999') and ('deaths', '99999') were removed and bunch of new timeseries were added with FIPS such as 02999, 04999 etc.
```
git reset --hard origin/master
python ./run.py utils save-combined-csv --output-dir output/
python ./run.py utils save-combined-latest-csv --output-dir output/
git checkout tgb-fips-99999-no-more
python ./run.py utils save-combined-csv --output-dir output/
python ./run.py utils save-combined-latest-csv --output-dir output/
python ./run.py utils csv-diff …
```
> Less FIPS 99999

- pyseir/inference/model_fitter.py
Looks like we were accidentally raising an error on a single model fitter failure rather than carrying on.  This should allow the build to not fail if one region fails
> Dont raise error on model fit failure

- .github/workflows/deploy_api.yml
- libs/pipelines/api_pipeline.py
- test/libs/api_pipeline_test.py
As of right now, the frontend breaks on counties where there aren't any projections.  this is a temporary band-aid to skip regions where we don't have models for them so the api outputs will not break the current page.
> Disable outputting if model file is missing

- libs/pipelines/api_pipeline.py
It looks like the api build is getting killed because of an OOM kill. this will reduce the usage similarly as to how we do in pyseir by setting maxtasksperchild to 1.
> Adding max tasks per child to reduce memory consumptione

- libs/pipelines/api_pipeline.py
The API build has been failing due to OOM errors during API generation.  It seems like there are some orphan processes that are accumulating memory usage on the build machines which may be the culprit.
Until I have a bit more time to look into it, I'm going to disable the multiprocessing during persisting.
> Removing parallelization of writes

- libs/datasets/combined_dataset_utils.py
- requirements.txt
- requirements_test.txt
- test/libs/datasets/combined_dataset_utils_test.py
* rm unused moto and boto3 imports and in `requirements_test.txt` and `requirements.txt`
* add `identify` to requirements_test.txt fixing `'Type tag 'jupyter' is not recognized.'`. See https://covidactnow.slack.com/archives/C0110QQAPJA/p1594827445123500
* upgrades pre-commit to latest release
> requirements update to rm moto and add identify

- libs/datasets/combined_datasets.py
- libs/datasets/dataset_base.py
- libs/datasets/latest_values_dataset.py
- libs/datasets/sources/cds_dataset.py
- libs/datasets/timeseries.py
- libs/functions/generate_api.py
- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/ensembles/ensemble_runner.py
- pyseir/parameters/parameter_ensemble_generator.py
- test/beds_dataset_test.py
- test/cds_dataset_test.py
- test/combined_dataset_test.py
- test/dataset_utils_test.py
- test/test_pyseir_end_to_end_test.py
* adds DatasetBase.yield_records, replacing `records` property that breaks in a future PR
* replaces use of `get_us_latest_for_state` with 2 digit code passed to `get_records_for_fips` 
* adds `test_fill_fields_with_data_source_nan_overwrite` that exercises the unexpected current behavior when combining datasets
* make get_subset aggregation_level parameter optional, it was required
* add `_` prefix to some functions that are internal to a class
> add DatasetBase.yield_records

- data/latest.csv
- data/latest.json
- data/timeseries.json
- libs/datasets/combined_datasets.py
- libs/datasets/dataset_filter.py
- libs/datasets/latest_values_dataset.py
- libs/datasets/sources/jhu_dataset.py
- libs/datasets/timeseries.py
- test/combined_dataset_test.py
* sort columns and rows in LatestValuesDataset before writing
* drop `index` column in LatestValuesDataset
* Dropping rows without FIPS in Timeseries, as produced by JHU but hard to filter in data source class because of the cleanup done in the timeseries class
`data/timeseries.csv` is identical.
`git show master:data/latest.csv | git lfs smudge > data/latest-master.csv` and then in jupyter: 
```
import pandas as pd
from covidactnow.datapublic import common_df
from libs.datasets.common_fields import CommonFields
path = 'data/latest-master.csv'
df = common_df.sort_common_field_columns(pd.read_csv(path, dtype={CommonFields.FIPS: str}).set_index(CommonFields.FIPS).sort_index())
df.to_csv(path, date_format="%Y-%m-%d", index=True, float_format="%.12g")
```
and the only difference is the empty …
> fix latest combined column order

- pyseir/rt/infer_rt.py
- test/infer_rt_test.py
This PR combines multiple points where we use the include_deaths flag into one flag. The data loading setup steps will also exit if neither case nor death data meet any of the filtering requirements. This makes it clearer where infer_rt "failed to generate output" by separating cases where we gave it no input from cases vs where it failed to find a solution given the non-empty input.
This should have a small speedup in the infer_rt code because (1) the engine won't be initialized on empty input data and (2) the include_deaths flag will short-circuit the engine from calculating the deaths based rt (which is dropped at the end by default).
> Infer Rt Flag and Logging Cleanup

- pytest.ini
- test/cli/data_cli_test.py
- test/combined_dataset_test.py
- test/infer_rt_test.py
- test/libs/api_pipeline_test.py
- test/test_pyseir_end_to_end_test.py
I want a way to easily run the fast tests so I don't need to wait as long to see the failures when the code is horribly broken. https://docs.pytest.org/en/stable/mark.html#registering-marks suggests adding a slow marker. `pytest --durations=50 test` got me a list of the slow tests and now `pytest -m 'not slow' test` finishes in about 6 seconds.
> add pytest.mark.slow to tests that take over 1s

- pyseir/load_data.py
- pyseir/rt/infer_rt.py
Some counties in Florida have erroneously reported test data that was not caught by our test correction filters. This tightens up filter restrictions as a first step towards a more robust pipeline.
https://trello.com/c/88PFNVhy/325-florida-infection-rate-wild-ride
> Fix the Florida Negative Negative_Tests Edge Case

- .github/workflows/daily_build.yml
- .github/workflows/deploy_api.yml
- .github/workflows/update_repo_datasets.yml
- README.md
- tools/build-snapshot.sh
This splits deploy_api.yml into 2 workflows.  
* deploy_api.yml is now only triggered via repository_dispatch and can be provided a branch to run on in the client payload.
* daily_build.yml is triggered on the preexisting schedule and just triggers the deploy_api.yml repository_dispatch.
NOTE:
1. I left the COVID_DATA_PUBLIC plumbing as-is even though it probably should be cleaned up.  But I got nervous because a) I don't know the state of the raw data QA, and b) I don't know if Natasha's early warning ML stuff is going to need it still.
2. I decided to defer adding the the ability to load older datasets (timeseries.csv / latest.csv), since you can always just create a temp branch with the older timeseries data.
> Make it easy to kick off a snapshot from an arbitrary branch / commit.

- libs/datasets/sources/nytimes_dataset.py
- test/libs/datasets/sources/nytimes_dataset_test.py
Removes CT case backfill from the NYTimes dataset.  
Cases are removed weighted on number of cases that day, see: https://trello.com/c/rPiM6UF4/333-adjust-ct-case-data-based-on-reported-backfill-vs-current-cases
> Adding in logic to remove CT case backfill

- run.sh
This doesn't actually 100% work because the build machines don't have jq installed, but I pinged @raygilbert about that so it should work soon. 😁   It should be safe to merge as-is though.
> Extract actual covid-data-public hash when generating snapshot version.json

- libs/datasets/__init__.py
- libs/datasets/latest_values_dataset.py
- pyseir/backtest/backtester.py
- pyseir/cli.py
- pyseir/ensembles/ensemble_runner.py
- pyseir/inference/fit_results.py
- pyseir/inference/initial_conditions_fitter.py
- pyseir/inference/model_fitter.py
- pyseir/inference/whitelist_generator.py
- pyseir/load_data.py
- pyseir/models/suppression_policies.py
- pyseir/reports/county_report.py
- pyseir/reports/state_report.py
- pyseir/utils.py
- test/mocks/inference/load_data.py
A couple things this PR accomplishes:
* removes all state level data access functions in load_data - everything is accessed through fips.
* Start removing most of the county_metadata references.  County metadata is another source that goes outside of our traditional data pipeline.  Removing the references helps streamline some of the pyseir code.  That source has always been very opaque to me.
* One of the confusing things is that we use the full state name in a lot of locations when we should be using fips or the ISO 2 abbreviated name.  I start to try to make it more explicit where we do that in this PR.  I'd like to take another pass through in a separate PR to finish that cleanup.
* It seems we only really use county metadata in the ensemble_runner for age distribution.  Do we …
> Pyseir location cleanup + start of removing county_metadata

- pyseir/rt/utils.py
We got a request to limit the aggregated counties to a specific 5, instead of the 8 that are part of the greater CBSA.
Here are the individual timeseries:
Here is the difference between aggregating the raw data versus a population-weight average. The current solution is a population-weighted average and shows very little difference in recent rt predictions.
> Update Counties to Include in Greater New Orleans Infer Rt Aggregate

- .github/workflows/update_repo_datasets.yml
- cli/data.py
- libs/google_sheet_helpers.py
- libs/qa/data_availability.py
- notebooks/data_availability.ipynb
- requirements.txt
- test/libs/data_availability_report_test.py
This computes and builds the [data availability sheet](https://docs.google.com/spreadsheets/d/1Z2wy8X9Xp1aWfXNYetPrr1FWNKN5Fraw3MVGMsHBFfc/edit?usp=sharing) from a command line: `./run.py data update-availability-sheet`.
It currently requires login via a service account token. When I add this onto the build token, we can base 64 encode the json file and store it in a github actions secret `GOOGLE_SHEETS_SERVICE_ACCOUNT_DATA`.  
I would like to do a bit more work to make it more dynamic, there are a couple hard coded ranges that are based on the specifics of the sheet. But other than that this PR should be good for a review
> Add data availability sheet

- libs/qa/dataset_summary.py
- libs/qa/dataset_summary_gen.py
- test/libs/dataset_summary_test.py
`dataset_summary_gen.py` depended on the order of the indexes set in `summarize_timeseries_fields` but it wasn't tested. This PR adds a test and changes the indexing to add only dates. My next PR adds another caller to dataset_summary_gen which can't as easily set the same index.
> change indexing of summarize_timeseries_fields and add test

- libs/datasets/sources/jhu_dataset.py
This was a bit annoying - looks like the recovered cases were added to a single fips in the 8/11 data, which was causing the source data to fail.  The fips has historically been none, so i just removed the fips for that record:
> Removing recovered cases from JHU data

- libs/datasets/combined_datasets.py
I'm not sure how far to go in the JHU excision, but we only include it in the recovered field.  
1. Recovered data is not used anywhere.
2. the recovered data that JHU has is not useful - it mainly only includes covered as an aggregate value for the entire country.
Should I go ahead and delete the JHU data source and associated tests? I would feel better if we were generating a single cleaned up timeseries file in covid-data-public?
> Remove JHU from combined datasets

- cli/data.py
- data/latest.json
- data/timeseries.json
- libs/datasets/combined_datasets.py
- libs/datasets/data_source.py
- libs/datasets/dataset_base.py
- libs/datasets/dataset_utils.py
- libs/datasets/latest_values_dataset.py
- libs/datasets/timeseries.py
- libs/notebook_helpers.py
- test/combined_dataset_test.py
* Moves code that changes a `DataSource` into a `DatasetBase` from combined_datasets, latest_values_dataset.py, timeseries.py to data_source.py.
* Load data sources before calling _build_combined_dataset_from_sources so that the loaded values can be used in multiple calls. Because `DataSource.latest` sometimes calls `DataSource.timeseries` the cache saves a bunch of processing time, reducing time as measured by `/usr/bin/time -v ./run.py data update` from 6 to 5 minutes.
* Make sure geo data columns in the wide-data DataFrame are created in a deterministic manner and sorted to match existing data.
`./run.py data update` re-generates the existing contents of `data/` exactly.
> Share loaded data sources between latest and timeseries combined data

- libs/datasets/sources/covid_tracking_source.py
Don't think we need the validation in the loading function.  Maybe some value, but don't want it to block deploys.
> Removing assertions - underlying meaning of data shifted, so assertion no longer holds

- .github/workflows/update_repo_datasets.yml
Followup to https://github.com/covid-projections/covid-data-model/pull/613 because https://github.com/covid-projections/covid-data-model/actions/runs/209780506 failed with
```
The workflow is not valid. .github/workflows/update_repo_datasets.yml (Line: 94, Col: 15): The expression is not closed. An unescaped ${{ sequence was found, but the closing }} sequence was not found.
```
> fix template, second try

- .github/workflows/update_repo_datasets.yml
https://github.com/covid-projections/covid-data-model/pull/614 didn't work... https://github.com/covid-projections/covid-data-model/actions/runs/209851636 failed with
```
The workflow is not valid. .github/workflows/update_repo_datasets.yml (Line: 94, Col: 15): Unrecognized named-value: 'DATA_AVAILABILITY_URL'. Located at position 1 within expression: DATA_AVAILABILITY_URL
```
This change copies https://github.com/covid-projections/covid-data-public/blob/master/.github/workflows/update_data.yml#L75 though I don't see that syntax for accessing env documented at https://docs.github.com/en/actions/reference
> another workflow syntax fix

- .github/workflows/deploy_api.yml
- cli/api.py
- tools/build-snapshot.sh
https://github.com/covid-projections/covid-data-public/blob/master/covidactnow/datapublic/common_init.py#L74
We initialize the sentry environment with the `SENTRY_ENVIRONMENT` environment variable.  setting that per branch so that we can control alerts and not send noisy alerts for test builds
> Setting sentry environment to allow configuration of sentry alerts per environment

- libs/datasets/custom_aggregations.py
- test/data_validation_test.py
By setting min_count to 1, it requires 1 non-na number to be present to produce a value.
> Ensure that NaNs accross all fields stay NaN

- libs/datasets/combined_datasets.py
- libs/datasets/timeseries.py
- test/combined_dataset_test.py
- test/libs/datasets/timeseries_test.py
This PR moves combined_datasets.get_timeseries_for_fips columns and min_range_with_some_value logic to TimeseriesDataset.get_columns_and_date_subset so it can be run on data not read with combined_datasets
> add TimeseriesDataset.get_columns_and_date_subset

- libs/pipeline.py
- pyseir/cli.py
- pyseir/deployment/webui_data_adaptor_v1.py
move pipeline.RegionalWebUIInput to webui_data_adaptor_v1.RegionalInput. This avoids an import cycle is it adds more dependencies and reduces the size of https://github.com/covid-projections/covid-data-model/pull/639.
> move pipeline.RegionalWebUIInput to webui_data_adaptor_v1

- libs/series_utils.py
- libs/top_level_metrics.py
- test/libs/series_utils_test.py
- test/libs/top_level_metrics_test.py
Wanted to get this in to make some of the testing easier/make it easier to pass around individual series rather than dataframes
> Switching to use a datetime index to make passing around data more lightweight

- libs/top_level_metrics.py
- test/libs/api_pipeline_test.py
- test/libs/top_level_metrics_test.py
caused this:
https://sentry.io/organizations/covidactnow/issues/1861469979/?project=5203044&query=is%3Aunresolved
> Setting the index to always be named date in top level metrics

- cli/api.py
This will start generating API outputs for the mariana islands.  I'm going to wait until the other pyseir changes get settled a bit more before adding it to the modeling output.
> add mariana islands to API output

- pyseir/cli.py
- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/ensembles/ensemble_runner.py
- pyseir/utils.py
Removes `RunMode`, no longer used. This change is extracted from https://github.com/covid-projections/covid-data-model/pull/652
> rm RunMode

- cli/api.py
This reverts commit 04431119984de90e0e932f7cb4df5c5f9ac72f59.
Turns out the frontend does work with mariana islands
> Revert "Revert "add mariana islands to API output (#653)""

- libs/datasets/sources/jhu_dataset.py
- test/combined_dataset_test.py
Recovered was still causing a problem because all values are zero.  There's a more elegant approach, but since we don't actually use them, i'm excluding it as a column
> Fixing JHU failing tests

- pyseir/cli.py
- test/pyseir_end_to_end_test.py
This separates running the pipelines from writing the output of the pipelines.  I was using the `--states-only` command and I realized that it wasn't writing the pipeline output.
> separating out running the pipelines from saving to disk

- api/can_api_definition.py
- libs/datasets/sources/can_pyseir_location_output.py
- libs/functions/generate_api.py
- libs/icu_headroom_metric.py
- pyseir/deployment/webui_data_adaptor_v1.py
- test/pyseir_end_to_end_test.py
The origin of this PR is I was seeing zeros for the latest estimated current icu count in the API.  I looked into it, and saw that the estimated icu series (taken from pyseir webui output) has 0s after the icu calc data ended rather than NAs.  We were treating this as a value and reporting that "current icu covid patients" were 0. 
We were filling nan's with 0s, so it was not possible to tell where the estimated icu value ended when computing the top level metrics.  
I feel pretty okay with this - I think we filled with zeros initially because of the weird output format we were writing. this should help us disambiguate between values with 0 and missing values
> Dont fill NAs with zeros in WebUI output

- pyseir/deployment/webui_data_adaptor_v1.py
This PR addresses issue https://trello.com/c/bIYt1RkT/426-webui-date-debug.
The infection rate can return an empty dataframe, which is not correctly handled in the current version.
> WebUI Handle RT Empty Results

- cli/data.py
- libs/datasets/combined_datasets.py
- libs/datasets/dataset_utils.py
- libs/datasets/latest_values_dataset.py
- libs/datasets/timeseries.py
- libs/pipelines/api_pipeline.py
- libs/top_level_metrics.py
- pyseir/inference/infer_t0.py
- pyseir/inference/model_fitter.py
- pyseir/inference/whitelist.py
- pyseir/load_data.py
- test/combined_dataset_test.py
- test/dataset_utils_test.py
- test/pyseir/load_data_test.py
- test/timeseries_test.py
* rm some unused methods of LatestValuesDataset and TimeseriesDataset
* replace TimeseriesDataset.get_data calls with get_subset(...).data
* rename make_binary_array to make_rows_key
* add types in a few places
> rm unused dateset methods

- libs/datasets/combined_datasets.py
- libs/pipeline.py
- pyseir/cli.py
- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/ensembles/ensemble_runner.py
- pyseir/inference/model_fitter.py
- pyseir/rt/infer_rt.py
- pyseir/utils.py
- test/infer_rt_test.py
- test/pyseir/icu/infer_icu_test.py
- test/pyseir_end_to_end_test.py
I ran into some gnarly import loops when using `Region` in more places. This refactor will hopefully break them and simplify a followup PR.
* mv pipeline.RegionalCombinedData to combined_datasets.RegionalData
* change access to the class to always use name `combined_datasets.RegionalData`
> mv pipeline.RegionalCombinedData to combined_datasets

- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/inference/model_fitter.py
- pyseir/inference/model_plotting.py
- test/pyseir_end_to_end_test.py
fix errors seen in https://github.com/covid-projections/covid-data-model/runs/1113246179
PR 678 removed run_artifact_path_to_read and run_artifact_path_to_write but I missed a caller. The tests don't run model_plotter code because of some weird multiprocessing issues with matplotlib on macs.
> Fix for PR 678

- .github/workflows/update_repo_datasets.yml
- cli/data.py
- data/external_forecasts.csv
- libs/datasets/sources/forecast_hub.py
Paired with https://github.com/covid-projections/covid-data-public/pull/123.
Makes a copy of the external forecasts (currently only the ensemble from ForecastHub) into the data directory of covid-data-model.
The move is currently a simple copy, since no other external forecast streams are currently being combined.
> Copy External Forecasts from covid-data-public to covid-data-model

- cli/data.py
- libs/datasets/sources/covid_tracking_source.py
* in CovidTrackingDataSource don't change data to Int64 because it causes "TypeError: reduction operation 'argmax' not allowed for this dtype" when the data is passed to _save_field_summary without taking a round-trip to disk.
* remove roundtrip to disk.
Making only the data.py change caused the error and a run of `python ./run.py data update` with the `covid_tracking_source.py` change re-generated identical data in `data/`.
> make summary from memory instead of disk

- libs/datasets/combined_datasets.py
- test/combined_dataset_test.py
- test/dataset_utils_test.py
* factors out _merge_field from combined_datasets._merge_data
* fixes 'Working field' log that included previous dataset name
* removes `combined_datasets.Override` since we seem to only use BY_TIMESERIES
> combined_datasets small cleanups

- libs/datasets/combined_datasets.py
This PR removes NevadaHospitalAssociationData from combined_datasets.
See https://covidactnow.slack.com/archives/C0110QQAPJA/p1600699303003900
Tested by running `python ./run.py data update` and comparing `data/latest.csv` and `data/timeseries-wide-dates.csv` with the master data. latest has lots of changes in NV that I'm guessing are reasonable. timeseries has changes in `current_ventilated` only with NV state now coming from covid_tracking and counties from Valorum and lost the variable in a few counties (Esmeralda, Eureka, Storey).
> rm NevadaHospitalAssociationData from combined_datasets

- pyseir/inference/model_fitter.py
- pyseir/load_data.py
- test/pyseir/inference/model_fitter_test.py
- test/pyseir/load_data_test.py
This PR changes get_hospitalization_data to return a raw DataFrame instead of MultiRegionTimeseriesDataset. This reduces the number of ways MultiRegionTimeseriesDataset is used, making changing it easier.
Change `test_get_pyseir_fitter_initial_conditions_none` to use a real FIPS so a future change is easier.
> Pass around hospitalization data in a raw DataFrame

- api/__init__.py
- api/awsauth/.gitignore
- api/awsauth/README.md
- api/awsauth/api_key_repo.py
- api/awsauth/auth_app.py
- api/awsauth/dynamo_client.py
- api/awsauth/serverless.yml
- requirements.txt
This is preliminary code involved for handling API auth.
Components:
* Uses two lambda functions: one to register emails and provide a key, another to check that the API key included in the request is valid.
* Stores email/api key pairs in a DynamoDB table
* Uses the serverless framework to deploy lambda functions.  lets us easily create different "stages" or envrionments so we can develop locally and not modify the prod api until ready. 
This hooks up to our API Gateway which is pretty manually put together.  I'd love to add that setup to the cloudformation resources, but will take a bit too much time right now.  
Since this code is deployed independently, I don't think it quite makes sense to have it integrate with the rest of the setup (i.e. share requirements, maybe live in libs). …
> Adding api auth

- api/can_api_v2_definition.py
- api/docs/open_api_schema.json
- api/schemas_v2/Actuals.json
- api/schemas_v2/ActualsTimeseriesRow.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/HospitalResourceUtilization.json
- api/schemas_v2/Metrics.json
- api/schemas_v2/MetricsTimeseriesRow.json
- api/schemas_v2/MetricsTimeseriesRowWithHeader.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/update_open_api_spec.py
- cli/api.py
- libs/base_model.py
- test/libs/base_model_test.py
@mikelehen brought up a good point that it is strange that we have the fields as being possibly not included, since all fields are currently included right now.
I ended up going down a bit of a rabbit hole, but long story short is that pydantic doesn't actually support outputting a field that is typed: `Optional[int]` as being null or int.  This PR implements some manual tweaking to identify when there is a required field that can be either null or a value and modifying the resulting schema.
It will make the typing more clear on the website
> Changing API Typing to be Required fields with nullable values

- libs/datasets/sources/covid_tracking_source.py
* Changes `CovidTrackingDataSource` to read timeseries.csv, which was parsed in the covid-data-public repo
Checked that my local covid-data-public repo is at sha in `data/multiregion.json` + https://github.com/covid-projections/covid-data-public/pull/135 then ran `python ./run.py data update --summary-filename=''`  and checked that `multiregion.csv` was not modified.
> covid tracking from public repo

- libs/icu_headroom_metric.py
This PR addresses issue https://trello.com/c/T15w5VLq/418-nj-icu-occupancy-rate-nonsensical.
> Patch NJ Typical ICU as Quick Fix

- libs/pipelines/api_v2_pipeline.py
This shaves a good 15 min off the deploy.  API v2 generation now takes 7 min instead of 23 min.
> Adding pool back to processing

- api/README.V1.md
- api/schemas/Actuals.json
- api/schemas/ActualsTimeseriesRow.json
- api/schemas/AggregateFlattenedTimeseries.json
- api/schemas/AggregateRegionSummary.json
- api/schemas/AggregateRegionSummaryWithTimeseries.json
- api/schemas/ICUHeadroomMetricDetails.json
- api/schemas/Metrics.json
- api/schemas/MetricsTimeseriesRow.json
- api/schemas/PredictionTimeseriesRow.json
- api/schemas/PredictionTimeseriesRowWithHeader.json
- api/schemas/Projections.json
- api/schemas/RegionSummary.json
- api/schemas/RegionSummaryWithTimeseries.json
- api/schemas/ResourceUsageProjection.json
- api/schemas/ResourceUtilization.json
- libs/update_readme_schemas.py
- requirements.txt
Updating pydantic to 1.6.1.  
The enum handling changed a bit in the latest version.  Also, it looks like the generated schemas in master for v2 were built with 1.6.1 so nothing changed for the new api.
This is definitely a hacky fix - not great code but we should be removing it soon when we yank out API v1.
Regenerated the schemas with `./run.py api update-schemas`
> Updating to pydantic 1.6.1 and fixing enum handling

- libs/datasets/combined_datasets.py
- libs/datasets/dataset_base.py
- libs/datasets/latest_values_dataset.py
- libs/datasets/timeseries.py
- pyseir/cli.py
- pyseir/deployment/webui_data_adaptor_v1.py
- pyseir/rt/infer_rt.py
- test/infer_rt_test.py
- test/libs/datasets/combined_dataset_utils_test.py
- test/libs/datasets/timeseries_test.py
- test/libs/generate_api_test.py
- test/libs/generate_api_v2_test.py
This reverts commit 7bb086bc2817b78ef1b938e4453713b8e0bd9db9.
This is temporary, seems to be causing https://sentry.io/organizations/covidactnow/issues/1957780407/?project=5203044&query=is%3Aunresolved
> Revert "remove FIPS from infer_rt and NOLA patch (#731)"

- cli/api.py
- cli/data.py
- libs/datasets/timeseries.py
- libs/icu_headroom_metric.py
- libs/pipelines/api_v2_pipeline.py
- test/libs/api_v2_pipeline_test.py
- test/libs/datasets/timeseries_test.py
This is the subset of https://github.com/covid-projections/covid-data-model/pull/728 that is not expected to change the output.
* Rename `MultiRegionTimeseriesDataset.merge` to `append_regions`
* Add `MultiRegionTimeseriesDataset.join_columns` and `iter_one_regions`
* Change `api_v2_pipeline.RegionalInput` to get combined data as OneRegionTimeseriesDataset parameters instead of loading it from disk to a RegionalData
* Change how generate-api-v2 creates `api_v2_pipeline.RegionalInput` to use  `iter_one_regions` which makes a single groupby call for each MultiRegion instead of a query for each region. With this making the inputs for all regions takes ~10 seconds.
> Add MultiRegion iterator

- .github/workflows/deploy_docs.yml
- .github/workflows/label_api_snapshot.yml
This adds a cloudfront cache invalidation to the latest api changes.  Without it, we may serve latest data from the cloudfront cache
> Invalidate cloudfront on latest + docs deploy

- cli/data.py
- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
This updates the new cases logic to not throw away the first case.  Small logic change before we can use it in a couple of other places.
> Update new case logic to not throw away first case

- .github/workflows/update_repo_datasets.yml
Adds an option in the dataset updater to optionally trigger api build on dataset update.
> Adding ability to trigger api build from github action

- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
- test/libs/test_positivity_test.py
This PR is the timeseries part of https://github.com/covid-projections/covid-data-model/pull/737
* Adds provenance to OneRegionTimeseriesDataset
* Changes `MultiRegionTimeseriesDataset.from_csv` to read provenance data if `to_csv` wrote it.
Tests pass.
Only change introduced by `python ./run.py data update --summary-filename=''` is renaming `value` column in `data/multiregion-provenance.csv` to `provenance`.
> provenance read and write

- api/awsauth/awsauth/api_key_repo.py
- api/awsauth/awsauth/auth_app.py
- api/awsauth/serverless.yml
Adds an attribute to a user indicating whether or not they registered/retrieved an API key using the CRS.  
In the CRS script, I add a parameter in the register body to indicate that is where the registration is coming from.
> adding covid response simulator user tracking to signup

- libs/datasets/dataset_utils.py
- libs/datasets/timeseries.py
- test/dataset_utils_test.py
- test/libs/datasets/timeseries_test.py
With the way things work, we still need to manually maintain the latest value in the multi region dataset.
This adds logic to add new cases into that. 
I don't want to get in a habit of this custom logic.  @TomGoBravo and I have talked about ways to calculate that dataset on the fly better, but that logic requires more refactoring, and I'd like for it to be separate from getting new cases out.
> Add new cases to latest value data structure

- api/can_api_v2_definition.py
- api/docs/open_api_schema.json
- api/schemas_v2/Actuals.json
- api/schemas_v2/ActualsTimeseriesRow.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/schemas_v2/RegionTimeseriesRowWithHeader.json
- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
Sometimes the new case series can be negative, to preserve the existing behavior this makes those nans.  It looks like this generally happens if a region switches from reporting probable -> confirmed cases or small adjustments.
> Remove negative new cases

- pyseir/rt/utils.py
This isn't even used in the return value
> Make outlier detection nan resistent

- .github/workflows/deploy_api.yml
Setting openblas threads to 1 drops pyseir runtime from 1hr 26 min -> ~10min (!).  I believe this is due to threading contention in openblas when using multiproccessing.  
I don't have a 100% detailed understanding for why it's this way, but https://github.com/xianyi/OpenBLAS/issues/731 gives some insight.  
There are some other optimizations i'd like to do that will bring the build time down to ~2min 30s, but will throw that in a separate PR
> Set openblas num threads to 1 to improve multiprocessing performance

- pyseir/cli.py
- pyseir/rt/constants.py
- pyseir/rt/infer_rt.py
- requirements.txt
This PR uses numba to speed up a scipy pdf function.  It speeds up the function call from 8ms per call to ~2ms per call. I checked and the input and output of the function was the same.
Loading the regions in parallel shaves off around 2 min of the run.  Now all of pyseir (rt calculation + icu calc) runs in 2 min 33 seconds.
> Use numba to speed up process matrix

- libs/datasets/sources/covid_county_data.py
- requirements.txt
Adds numexpr 2.7.1 to our dependencies.  This is [recommended](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#install-recommended-dependencies) by pandas and [according to the docs](https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html#enhancingperf-eval), "To benefit from using eval() you need to install numexpr."
That said, this PR has no meaningful perf impact (on `run.py data updata` or on full snapshot generation).  And in fact, to make our code work with numexpr I had to change one of our 2 uses of `eval()` and in doing so and measuring the perf impact I discovered that:
1. numexpr didn't affect the performance.
2. Avoiding eval() actually had better performance (saved ~0.07s, taking the …
> RFC: Install numexpr module per pandas recommendations.

- api/can_api_definition.py
- libs/top_level_metrics.py
Two little things that didn't get into https://github.com/covid-projections/covid-data-model/pull/737 ...
* add TestPositivityRatioMethod.COVID_TRACKING
* downgrade noisy log from info to debug
> Test positivity provenance in API followup

- libs/datasets/statistical_areas.py
- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
This PR removes `MultiRegionTimeseriesDataset.from_combined_dataframe` which is useful for parsing a CSV with metrics in columns but wasn't otherwise useful. Removing it reduces the number of ways that a `MultiRegionTimeseriesDataset` can be created.
> rm MultiRegionTimeseriesDataset.from_combined_dataframe

- api/can_api_definition.py
- api/docs/open_api_schema.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/Metrics.json
- api/schemas_v2/MetricsTimeseriesRow.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/schemas_v2/RegionTimeseriesRowWithHeader.json
- libs/datasets/combined_datasets.py
- libs/datasets/sources/cms_testing_dataset.py
- libs/datasets/sources/covid_county_data.py
- libs/datasets/timeseries.py
- libs/test_positivity.py
- libs/top_level_metrics.py
- test/combined_dataset_test.py
- test/libs/api_v2_pipeline_test.py
- test/libs/datasets/sources/covid_county_data_test.py
- test/libs/test_positivity_test.py
- test/libs/top_level_metrics_test.py
* Adds CMSTesting dataset.
* Modifies Valorum dataset to drop test data from states we don't trust.
* Adds a `PassThruMethod` to test_positivity.py that lets us use the `test_positivity` column as-is.
> Use CMS as backfill for test positivity, and disable questionable counties from Valorum

- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
This is mostly just un-reverting the  "MultiRegion append_regions preserves provenance" change.
The very small fix to it is in https://github.com/covid-projections/covid-data-model/pull/787/commits/5f38158d56b5f52a4ca79035c03ade3c05d9d071
> Un-revert provenance commit and fix series name.

- .github/workflows/deploy_api.yml
Stops running updates for api v1.  The existing files in /latest should still remain, meaning you will still be able to download the existing api, but it will no longer update.
> Stop updating api v1

- libs/datasets/timeseries.py
- test/libs/datasets/combined_dataset_utils_test.py
- test/libs/datasets/timeseries_test.py
- test/libs/test_positivity_test.py
* rm combined_df property
* rename assert_combined_like to assert_dataset_like
* add drop_na_latest to fix tests that depended on combined_df creating columns
This follows up on https://github.com/covid-projections/covid-data-model/pull/784
> rm combined_df property

- libs/datasets/statistical_areas.py
- libs/datasets/timeseries.py
- libs/test_positivity.py
- test/libs/datasets/timeseries_test.py
- test/libs/generate_api_test.py
- test/libs/generate_api_v2_test.py
- test/libs/test_positivity_test.py
This PR simplifies the MultiRegionTimeseriesDataset interface, easing future changes to it.
-  mark latest_data and provenance attributes as private with single underscore
-  replace use of `from_timeseries_df(provenance=...)` with call to new add_provenance_series method
-  in `test_recent_days replace` direct access `to _provenance` with getting it from get_one_region return value.
-  rename append_latest_df to add_latest_df
-  rename append_provenance_csv to add_provenance_csv
-  remove some access to latest values in effort to remove latest values
-  drop_column_if_present using _latest_data instead of latest_data_with_fips
> MultiRegion more private attributes

- libs/datasets/sources/covid_county_data.py
The CMS rates are way lower and inline with the state-level positivity, so I think we should use CMS.
https://trello.com/c/e9o3mhjW/585-try-switching-to-cms-test-positivity-data-for-rhode-island
Demo snapshot here (FYI- also includes reenabling OR, NE, and CA HHS data): https://covid-projections-git-mikelehen-demo-snapshot.covidactnow.vercel.app/internal/compare
> Disable RI county test positivity from covid-county-data, since the rates seem to be way higher than CMS.

- .github/workflows/deploy_api.yml
- tools/maybe-trigger-label-api.sh
- tools/maybe-trigger-web-snapshot-update.sh
This removes the time restrictions to kick of snapshot PRs on the website and label api.
> Remove time restrictions on label-api and pr-generation

- libs/datasets/timeseries.py
- libs/test_positivity.py
- test/libs/datasets/timeseries_test.py
This PR helps to pave the way for some test positivity cleanup which will make more use of MultiRegionDataset to pass around timeseries and provenance information together.
* Adds `MultiRegionDataset.timeseries_wide_dates` which returns the timeseries in a DataFrame with date columns and from_timeseries_wide_dates_df that makes a new dataset from such a DataFrame.
* Makes sure the timeseries column axis has a name. `stack` uses the name for the new index level.
* Removes a stale comment in _trim_timeseries
* Adds `MultiRegionDataset.drop_stale_timeseries`
> add MultiRegion.drop_stale_timeseries

- cli/api.py
- libs/datasets/timeseries.py
- libs/test_positivity.py
- test/libs/datasets/timeseries_test.py
- test/libs/test_positivity_test.py
This PR follows https://github.com/covid-projections/covid-data-model/pull/815 with a bit more paving the way for some test positivity cleanup
* drop columns that are all na and sort by index when writing test positivity debug output
* add generate_test_positivity output_dir to make changing output path easier
* make test_positivity_test.test_recent_days one day stricter so off-by-one bugs with recent_days are found
* change `drop_stale_timeseries` to also drop provenance info for dropped timeseries
* remove a use of `MultiRegionDataset.data` in `_timeseries_sorted_by_location_date`
> test positivity cleaner output and provenance cleanup

- libs/datasets/sources/cms_testing_dataset.py
- libs/datasets/sources/covid_care_map.py
- libs/datasets/sources/nytimes_dataset.py
- libs/datasets/sources/test_and_trace.py
* Removes covid-care-map parsing code that has been moved to covid-data-public in https://github.com/covid-projections/covid-data-public/pull/169
* some simplification of COMMON_FIELD_MAP and INDEX_FIELD_MAP in a couple other datasources
Reproduced existing combined datasets output using `python ./run.py data update`
> rm covid-care-map parsing

- libs/datasets/combined_datasets.py
- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
This will soon change when we remove latest, but a quick patch to load both the timeseries and static values when loading the latest values dataset for the data availability report
> Use both static and timeseries fields in data availability sheet

- libs/notebook_helpers.py
Attempt at fix for error seen at https://covidactnow.slack.com/archives/C011Z21ST8V/p1607427998029100
Breakage was introduced by https://github.com/covid-projections/covid-data-model/pull/829
Stack trace from https://github.com/covid-projections/covid-data-model/runs/1517069782?check_suite_focus=true
```
File "/home/runner/work/covid-data-model/covid-data-model/covid-data-model/cli/data.py", line 190, in update_availability_report
data_sources_by_source_name = data_availability.load_all_latest_sources()
File "/home/runner/work/covid-data-model/covid-data-model/covid-data-model/libs/qa/data_availability.py", line 22, in load_all_latest_sources
sources = notebook_helpers.load_data_sources_by_name()
File "/home/runner/work/covid-data-model/covid-data-model/covid-data-model/libs/notebook_helpe …
```
> attempt at fixing load_data_sources_by_name

- libs/datasets/dataset_utils.py
- libs/datasets/timeseries.py
- pyseir/cli.py
- test/libs/datasets/timeseries_test.py
This PR helps me test https://trello.com/c/EyISOtVY/623-country-aggregation-breaking-pyseir-output-and-doesnt-output-api-files-properly
Running the following generates API output for one CBSA.
```
python ./pyseir/cli.py build-all --location-id-matches='(iso1\:us\#cbsa\:10100|.+\#fips\:46013|.+\#fips\:46045)' --generate-api-v2 --output-dir output-cbsa-10100
```
> add pyseir build-all --location-id-matches

- libs/datasets/statistical_areas.py
- libs/datasets/timeseries.py
- pyseir/run.py
This fixes a couple issues with the aggregator:
1. I updated the column used for test positivity. It was simply summing the new test positivity columns, not good.
2. NYC CBSA was missing.  This is because the boroughs are aggregated, so the missing counties made all columns be null. this is very much a short lived fix, but in the email mentioning the NYC switch, we refer to the new CBSA, so I'd like this to be included before sending out and not have everyone query a missing CBSA.
> Fix additional test positivity columns and NYC CBSA aggregation

- .github/workflows/deploy_api.yml
Would like to disable auto-labeling just so we don't accidentally update latest before we're ready to roll it out
> Disable auto-label

- .github/workflows/deploy_api.yml
Should be good to go to auto-label the api now with NYC broken out
> Revert "Disable auto-label (#852)"

- pyseir/load_data.py
- pyseir/rt/infer_rt.py
This was throwing [an error](https://sentry.io/organizations/covidactnow/issues/2082300724/?project=5203044&query=is%3Aunresolved) - not 100% sure what changed that started it up, but PR doesn't have death data for counties and this was breaking the remove padded nans.
> Remove unused deaths from new case calculation that was breaking for PR

- .github/workflows/CI_test_deploy_api.yml
- .github/workflows/deploy_api.yml
- .github/workflows/python_unit_tests.yml
- .github/workflows/update_api_usage.yml
- .github/workflows/update_repo_datasets.yml
- api/README.md
- binder/requirements.txt
- libs/pipeline.py
- raw_data_QA/check_raw_case_death_data.py
- tools/maybe-trigger-web-snapshot-update.sh
Should not be merged until the main branch exists, but changes all covid-data-public master references to main
> Change references of covid data public master -> main

- libs/metrics/top_level_metrics.py
- test/libs/datasets/timeseries_test.py
- test/libs/metrics/top_level_metrics_test.py
This PR is part of https://trello.com/c/6ZPv7k9T/477-clean-up-redundant-test-positivity-calculation-code-api-vs-combined-dataset
* Changes `calculate_test_positivity` to run the smoothing itself and take a `OneRegionTimeseriesDataset` instead of raw DataFrame.
* Adds test helpers build_dataset and build_one_region_dataset to simplify making test data
Ran `python ./run.py api generate-test-positivity` in master and this branch. Compared results/output/test-positivity-all.csv and results/output/test-positivity-output.csv from each. They were identical.
> calculate_test_positivity takes Dataset

- libs/datasets/timeseries.py
- libs/metrics/test_positivity.py
- libs/metrics/top_level_metrics.py
- test/libs/metrics/test_positivity_test.py
- test/libs/metrics/top_level_metrics_test.py
This PR is part of https://trello.com/c/6ZPv7k9T/477-clean-up-redundant-test-positivity-calculation-code-api-vs-combined-dataset
* Changes the test_positivity `calculate` methods to read from a dataset class instead of raw DataFrame
* Adds cached data access methods in `MultiRegionDataset` to replace calculations that were done in `AllMethods.run`
* Adds `_make_result_dataset` which builds a Series used by add_provenance_series, replacing the call to `add_provenance_all`. This is a step towards copying provenance per location which will replace the hack of having a CommonField per source. 
* Extends `build_dataset` to use a new timeseries literal class to optionally set provenance info.
```
git checkout master
./run.py api generate-test-positivity --output-dir results/output-master/
git …
```
> Test positivity calculate takes dataset

- cli/data.py
- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
- test/test_helpers.py
This PR is part of https://trello.com/c/Cq2zNk2M/674-annotate-data-outliers-that-weve-flagged-in-the-ui
With this change annotations get all the way from the tail filter to the final combined data object. Next step will be writing and reading them and getting them to the API code.
* Adds method `MulitRegionDataset.append_tag_df`. 
* Tweaks `MulitRegionDataset.__post_init__` to explicitly check for dates instead of depending on `to_datetime` raising an exception. This catches places where a string representation of date gets into the index.
* Moves access to annotations from through `TailFilter.annotations_as_dataframe()` to `MulitRegionDataset.annotations_as_dataframe()`. 
* Adds test_helper code for tags/annotations
Ran the following commands to check that annotations made their way to …
> Move annotations into MultiRegionDataset.tag

- cli/api.py
- libs/metrics/test_positivity.py
- test/libs/metrics/test_positivity_test.py
This PR cleans up some test positivity tests to simplify a future change which makes more use of the provenance tag. This changes how the output files are written, but they are only used for debugging.
* changes most test_positivity_test to use TimeseriesLiteral so it is easier to set the provenance
* writes test_positivity final_result using timeseries_rows() instead of custom code
* writes a Mapping[timeseries.DatasetName, MultiRegionDataset] instead of custom test_positivity write.
* removes all_methods.all_methods_timeseries checks in test_positivity_test. 
In main ran `python ./run.py api generate-test-positivity --output-dir results/output-main/` and in this branch `python ./run.py api generate-test-positivity --output-dir results/output-tgb-positivity-test-cleanup` then compared …
> test_positivity_test TimeseriesLiteral

- test/combined_dataset_test.py
> in test_combined_county_has_some_timeseries_data allow test positivity to be enough to pass.

- libs/datasets/timeseries.py
- requirements_test.txt
- test/libs/datasets/combined_dataset_utils_test.py
- test/libs/datasets/timeseries_test.py
This PR makes the wide-dates files a little smaller and easier to read, as the last part of https://trello.com/c/6W0oakD2/711-github-usage-investigate-low-hanging-fruits
I'm also upgrading to the newest pytest to get the latest pytest.approx
> in wide-dates csv put most recent data on left, truncate decimals and extra commas. update pytest

- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
This PR is part of https://trello.com/c/Cq2zNk2M/674-annotate-data-outliers-that-weve-flagged-in-the-ui
* in drop_new_case_outliers add an annotation for each removed value
Ran `./run.py data update` which produced a 199k data/multiregion-annotations.csv up from 26k. Looking at `git difftool -t vimdiff --no-prompt main -- data/multiregion-annotations.csv` the diffs look as expected, adding a bunch of zscore_outlier in states and counties. A few regions have multiple outliers removed.
> Add annotations in drop_new_case_outliers

- api/can_api_v2_definition.py
- api/docs/open_api_schema.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/ICUHeadroomMetricDetails.json
- api/schemas_v2/Metrics.json
- api/schemas_v2/MetricsTimeseriesRow.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/schemas_v2/RegionTimeseriesRowWithHeader.json
- api/schemas_v2/RiskLevelTimeseriesRow.json
- api/schemas_v2/RiskLevels.json
- api/schemas_v2/RiskLevelsRow.json
- api/schemas_v2/TestPositivityRatioDetails.json
- libs/pipelines/api_v2_pipeline.py
- requirements.txt
This updates the version of pydantic (seems to shave 1 min of api build) + excluding unset fields, this primarily lets us remove `icuHeadroomDetails` and `testPositivityRatioDetails` from the json output, which shaves about 75MB off of the counties.timeseries.json file. 
Any field that is included but null (which is most fields) will be included in the output
> Update pydantic + Exclude unset fields in json serialization

- api/can_api_v2_definition.py
- api/docs/docs/updates.md
- api/docs/open_api_schema.json
- api/schemas_v2/Actuals.json
- api/schemas_v2/ActualsTimeseriesRow.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/schemas_v2/RegionTimeseriesRowWithHeader.json
- libs/build_api_v2.py
- libs/datasets/combined_datasets.py
- test/libs/generate_api_v2_test.py
This gets vaccination data flowing through to the API. Note that vaccinations completed won't have any data just yet, but now that the data is available, looks like it will sooon!
I also am filtering out including vaccination data before the date of first us vaccination.  
I confirmed that loading the timeseries in pandas works just fine with some records not having all of the fields.
> Add vaccines to api

- libs/datasets/tail_filter.py
- libs/datasets/timeseries.py
- libs/metrics/test_positivity.py
- test/libs/datasets/taglib_test.py
- test/libs/datasets/tail_filter_test.py
- test/libs/datasets/timeseries_test.py
- test/libs/metrics/test_positivity_test.py
- test/test_helpers.py
This PR builds towards https://trello.com/c/Cq2zNk2M/674-annotate-data-outliers-that-weve-flagged-in-the-ui
* Moves `date` from a field in the tag/annotation CSV and DataFrame to a field in the JSON content of annotations. This replaces the human readable strings buried in our data pipeline with flexible JSON content. The downside is processing the JSON in pandas is harder. The upside is this makes adding new attributes per annotation *much* easier. Removing the date will also make it easier to include all the annotations in the wide-dates CSV so we can later remove multiregion-annotations.csv.
> Change tag content to JSON

- api/can_api_v2_definition.py
- test/libs/generate_api_v2_test.py
This PR builds towards https://trello.com/c/Cq2zNk2M/674-annotate-data-outliers-that-weve-flagged-in-the-ui
Follow up to https://github.com/covid-projections/covid-data-model/pull/889
> fix Annotations in test_build_summary_for_fips

- api/can_api_v2_definition.py
- api/docs/docs/updates.md
- api/docs/open_api_schema.json
- api/schemas_v2/Actuals.json
- api/schemas_v2/ActualsTimeseriesRow.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/schemas_v2/RegionTimeseriesRowWithHeader.json
This PR builds towards https://trello.com/c/Cq2zNk2M/674-annotate-data-outliers-that-weve-flagged-in-the-ui
Follow up to https://github.com/covid-projections/covid-data-model/pull/889
* update updates log
* `./run.py api update-v2-schemas`
> Update log and API schemas

- libs/datasets/timeseries.py
- test/libs/datasets/timeseries_test.py
> make sure timeseries wide is actually a DatetimeIndex. add MultiRegionDataset.provenance_map.

- api/docs/docs/access.mdx
This updates the docs to add better examples for how to use the api.
Instead of showing a few examples, it groups the types of queries in a more easily understandable format I think.
> Update examples to better explain all of the available files in the API

- libs/update_api_user_metrics.py
good news, we have over 1k API users! The code was only equipped to handle the first page, so this paginates the response and will update with all active users.
Tested by running locally against the athena data that has more than 1000 rows
> Enable pagination for query results

- cli/data.py
- libs/datasets/sources/zeros_filter.py
- tests/libs/datasets/zeros_filter_test.py
This PR adds a filter to remove all-zero vaccine data, for https://trello.com/c/J3M0Ksb5/827-unmask-ohio-vaccination-data
Ran `./run.py data update` and `git difftool -t vimdiff data/multiregion-wide-dates.csv` to see that only data in OH counties and the tiny county of Loving, TX were dropped.
> add zeros_filter

- api/can_api_v2_definition.py
This PR add sources found in API build logging: https://github.com/covid-projections/covid-data-model/runs/1818041994
> Add TestAndTrace and CAN Scraper sources in API

- data/multiregion.json
- libs/datasets/combined_datasets.py
- libs/datasets/sources/can_scraper_state_providers.py
This PR is part of https://trello.com/c/PgOjusc7/846-etl-tn-county-vaccine-data-into-api
```
git difftool -t vimdiff data/multiregion-wide-dates.csv
```
finds vaccinations_completed_pct and vaccinations_initiated_pct added to TN counties and a few CBSA (most likely in TN too).
No other changes.
> add new vaccine pct fields in combined_datasets

- libs/datasets/taglib.py
- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
- tests/test_helpers.py
This PR is a big part of https://trello.com/c/lbiZpKwH/849-proposal-improve-the-provenance-link-so-that-we-can-show-a-source-urls-instead-of-a-data-class
* Adds `class SourceUrl(TagInTimeseries)` and an property to get them in `OneRegionTimeseriesDataset`
* Changes `test_helper.TimeseriesLiteral` to a frozen dataclass with some type conversion in `__init__`
* Adds `dataclass_with_default_init`, backport of code in Python 3.9
Instead of doing type conversion in `test_helper.TimeseriesLiteral` i could leave the attributes as one of 3 types and added properties provenance_as_list and source_url_as_list. Either is fine but I had to pick one.
> Add source_url tag

- tests/libs/generate_api_v2_test.py
> fix zscore_outlier data in generate_api_v2_test

- data/multiregion.json
- libs/datasets/data_source.py
- libs/datasets/sources/can_scraper_helpers.py
- libs/datasets/sources/can_scraper_state_providers.py
- libs/datasets/sources/can_scraper_usafacts.py
- libs/datasets/sources/cdc_testing_dataset.py
- libs/datasets/sources/cdc_vaccine_dataset.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
This PR is part of https://trello.com/c/lbiZpKwH/849-proposal-improve-the-provenance-link-so-that-we-can-show-a-source-urls-instead-of-a-data-class
It moves the files that are run in the this repo and will be modified to load source_url, into this repo.
* Move parquet transforms from covid-data-public repo to covid-data-model without changing the structure or names much
* Import the copied module as ccd_helpers to avoid changing the transform functions at all
* rename CovidCountyDataset to CanScraperLoader
Deleted the data from my local covid-data-public repo
```
deleted:    data/can-scrapers-state-providers/timeseries-common.csv
deleted:    data/testing-cdc/timeseries-common.csv
deleted:    data/vaccines-cdc/timeseries-common.csv
deleted:    scripts/ccd_helpers.py
deleted: …
```
> Move parquet transforms to covid-data-model

- libs/datasets/data_source.py
- libs/datasets/sources/can_scraper_state_providers.py
- libs/datasets/sources/can_scraper_usafacts.py
- libs/datasets/sources/cdc_testing_dataset.py
- libs/datasets/sources/cdc_vaccine_dataset.py
This PR is part of https://trello.com/c/lbiZpKwH/849-proposal-improve-the-provenance-link-so-that-we-can-show-a-source-urls-instead-of-a-data-class
replace CanScraperBase.TRANSFORM_METHOD with VARIABLES and a method that can be overridden. This will make it easier to have query_multiple_variables return source_url values that can be added to the MultiRegionDataset.
Ran `data update` and checked that identical output was produced.
> Move variables to a CanScraperBase attribute

- api/can_api_v2_definition.py
- libs/build_api_v2.py
- tests/libs/api_v2_pipeline_test.py
- tests/libs/generate_api_v2_test.py
This PR is part of https://trello.com/c/lbiZpKwH/849-proposal-improve-the-provenance-link-so-that-we-can-show-a-source-urls-instead-of-a-data-class
* Adds ￼source_url to API FieldAnnotations
* Adds annotations for vaccines which were in the API but never populated.
* Adds a tests to make sure all FieldAnnotations are populated
Changed to branch `git checkout tgb-849-add-source-url`, ran `./run.py data update` then switched back to this branch with updated data. Then ran `python pyseir/cli.py build-all --generate-api-v2 -s FL --fips 12011` and checked with `jq . output/county/12011.timeseries.json` that some URLs were added.
> source_url in API

- tests/libs/generate_api_v2_test.py
> add missing URL to fix tests/libs/generate_api_v2_test

- dash_app/__init__.py
- dash_app/dashboard.py
- run_dash.py
This PR is part of https://trello.com/c/s0ObL5ii/860-deploy-dashapppy-the-data-pipeline-dashboard
move dashboard code into new `dash_app/` directory, leaving `run_dash.py` in root directory of repo.
> move dashboard to dash_app/ and run_dash.py

- tests/libs/datasets/sources/cdc_testing_dataset_test.py
This is part of https://trello.com/c/lS3FplkP/869-delete-the-ccd-10-pipeline
This PR adds a test removed by https://github.com/covid-projections/covid-data-public/pull/207
> add test removed from covid-data-public

- services/webhook/hooks.json
- services/webhook/update.sh
All being well, this PR finishes https://trello.com/c/s0ObL5ii/860-deploy-dashapppy-the-data-pipeline-dashboard
There is a bug in older versions of webhook where it fails to find a command given relative to the working directory. An absolute path is ugly but works.
> work-around for https://github.com/adnanh/webhook/pull/327

- services/webhook/webhook.service
It looks like webhook sometimes confuses git futzing around with files as the file being removed and it doesn't read the new file, leaving it without any loaded webhook. Disable hotreload to avoid the problem.
Example from `sudo systemctl status webhook`:
```
Feb 18 16:24:01 data-pipeline-dashboard-1 webhook[17711]: [webhook] 2021/02/18 16:24:01 hooks file /home/tom/covid-data-model/services/webhook/hooks.json removed, no longer watching this file for changes, removing hooks that were load
Feb 18 16:24:01 data-pipeline-dashboard-1 webhook[17711]: [webhook] 2021/02/18 16:24:01         removing: pull-covid-data-model
Feb 18 16:24:01 data-pipeline-dashboard-1 webhook[17711]: [webhook] 2021/02/18 16:24:01 removed 1 hook(s) that were loaded from file …
```
> rm hotreload from webhook setup

- libs/datasets/combined_datasets.py
- libs/datasets/sources/cdc_vaccine_dataset.py
This adds CDC doses administered to combined datasets which will be used to help estimate CA vaccination county rates
> Add cdc doses administered

- tests/libs/datasets/custom_aggregations_test.py
- tests/libs/datasets/timeseries_test.py
This PR adds tests for pickle of MultiRegionDataset and running aggregate_to_new_york_city in attempt to catch problem in https://github.com/covid-projections/covid-data-public/pull/208
> Tests for 'cannot be pickled'

- libs/build_api_v2.py
- libs/datasets/taglib.py
- libs/datasets/timeseries.py
- tests/libs/api_v2_pipeline_test.py
- tests/libs/datasets/timeseries_test.py
- tests/libs/metrics/test_positivity_test.py
- tests/test_helpers.py
This PR is prep for https://trello.com/c/hSJN82y9/927-pipe-through-source-names-to-fe
* Extracts API code that makes `FieldSource` so it can be more easily replaced
* Renames ` TagInTimeseries` field `type` to `tag_type` so that `Source` can have `type` property.
* Adds `OneRegionTimeseriesDataset.tag_objects_series` for easier access to these, by type
> refactoring for adding source tag

- tests/libs/generate_api_v2_test.py
> add NY vacine source in test_build_summary_for_fips

- libs/datasets/sources/can_scraper_helpers.py
This PR is part of https://trello.com/c/hSJN82y9/927-pipe-through-source-names-to-fe
I got tired of waiting for tests to run on all the data and have seen this is a big chunk of combined dataset update too.
Benchmark taken with 
```
py-spy record --subprocesses -r 10 -o output/`date --iso-8601=minutes --utc`.svg -- pytest tests/libs/datasets/data_source_test.py
```
then looking at the count of samples in changed code.
> speed up CanScraperLoader._get_rows

- libs/datasets/sources/can_scraper_helpers.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
I stumbled on a problem with how we handle multiple observations with different ethnicity values when working on https://trello.com/c/hSJN82y9/927-pipe-through-source-names-to-fe. `pivot_table` does its default of returning a mean. This PR demonstrates the problem with a fast unittest.
> Add test with ethnicity aggregated with mean

- libs/build_api_v2.py
- tests/libs/api_v2_pipeline_test.py
This PR is part of https://trello.com/c/hSJN82y9/927-pipe-through-source-names-to-fe
Copies Source.name to FieldSource.name.
Extends an existing unittest.
Testing with this PR and https://github.com/covid-projections/covid-data-model/pull/969 with something like
```
python pyseir/cli.py build-all --generate-api-v2 --location-id-matches '.+fips:(48201|06073|12011)'
vimdiff output-before/county/12011.timeseries.json output/county/12011.timeseries.json
csvgrep -c location_id -m fips:12011 data/multiregion-wide-dates.csv  |csvcut -c location_id,variable,source
```
finds some new names in the output JSON, for example:
```
"vaccinationsInitiated": {
"sources": [
{
"type": "CANScrapersStateProviders",
"url": "https://floridahealthcovid19.gov/#latest-stats",
"name": "Florida Department of Health" …
```
> copy Source.name to FieldSource.name

- tests/combined_dataset_test.py
- tests/infer_rt_test.py
- tests/nowcast_seir_model_basic_test.py
- tests/nowcast_seir_model_end_to_end_test.py
- tests/original_seir_model_test.py
Mark tests found by `pytest -k 'not slow' --durations=50 tests` as taking more than a second as slow.
This brings `pytest -k 'not slow' tests` back down to about a minute.... not bad but not fast.
> mark more slow tests

- tests/libs/generate_api_v2_test.py
The test started failing when combined datasets was updated to add `name` when loading from `CanScraperLoader`.
> Update source names in generate_api_v2_test

- libs/datasets/combined_datasets.py
- libs/datasets/data_source.py
- libs/datasets/sources/can_location_page_urls.py
- libs/datasets/sources/can_scraper_state_providers.py
- libs/datasets/sources/can_scraper_usafacts.py
- libs/datasets/sources/cdc_testing_dataset.py
- libs/datasets/sources/cdc_vaccine_dataset.py
- libs/datasets/sources/cms_testing_dataset.py
- libs/datasets/sources/covid_care_map.py
- libs/datasets/sources/covid_tracking_source.py
- libs/datasets/sources/fips_population.py
- libs/datasets/sources/forecast_hub.py
- libs/datasets/sources/hhs_hospital_dataset.py
- libs/datasets/sources/hhs_testing_dataset.py
- libs/datasets/sources/nytimes_dataset.py
- libs/datasets/sources/test_and_trace.py
- libs/datasets/sources/texas_hospitalizations.py
- tests/combined_dataset_test.py
This PR is for  https://trello.com/c/rI3EQlS6/976-add-nytimes-source-name-to-annotations
* Adds SOURCE_NAME and SOURCE_URL, renames current name to SOURCE_TYPE
> DataSource attributes to support source names

- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
This PR is for dashboard PR https://github.com/covid-projections/covid-data-model/pull/958 and is one possible way to make a `pd.Series` of URLs in `source` tags.
* adds tag_objects_series to MultiRegionDataset
* fixes tag_objects_series handling of empty tag DF
* adds make_source_url_tags
> copy source tag to source_url

- libs/datasets/sources/cms_testing_dataset.py
- libs/datasets/sources/covid_tracking_source.py
- libs/datasets/sources/nytimes_dataset.py
This PR completes :crossed_fingers: https://trello.com/c/rI3EQlS6/976-add-nytimes-source-name-to-annotations
* Adds source name and URL to older data sources that are not part of the new CAN Scraper system
> Add static name and URL to non-CAN Scraper 

- api/can_api_v2_definition.py
- libs/build_api_v2.py
- tests/api/can_api_v2_definition_test.py
- tests/libs/api_v2_pipeline_test.py
- tests/libs/generate_api_v2_test.py
This PR addresses https://trello.com/c/g0fSP3MT/974-change-annotation-names-to-match-metric-names
* Adds Annotations for metrics
* Adds some test that will hopefully make maintaining these less dependent on us noticing problems
* Changes `build_annotations` to use two maps of constants instead of long list of hard-coded function calls
* Changes `test_annotation` to put duplicate URLs in new_cases instead of cases. Currently `cases` is used multiple times which produced multiple log warning calls and broke the log event check in the test.
> Add metric annotations

- dash_app/dashboard.py
This PR
* Adds enums for how regions and variables are aggregated and use them to parameterize `_agg_wide_var_counts`
* Add `AggregatedStats` to hold stats after they have been aggregated
* Expand population ratio URL coverage table to include, for each variable, portion of population that has some county data
* Add dropdown in Region section at bottom to include only a subset of variables
* Factor out dash_table_from_data_frame
> Dashboard browse by variable group and add timeseries county population ratio

- libs/datasets/data_source.py
- libs/datasets/sources/can_scraper_state_providers.py
- libs/datasets/sources/can_scraper_usafacts.py
- libs/datasets/sources/cdc_testing_dataset.py
- libs/datasets/sources/cdc_vaccine_dataset.py
- tests/libs/datasets/data_source_test.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
- tests/libs/datasets/taglib_test.py
- tests/test_helpers.py
This PR is part of https://trello.com/c/lvRFxC5y/932-get-dei-vaccination-data-into-api
* change can_scraper_helpers_test to call make_dataset instead of query_multiple_variables, so the value returned by query_multiple_variables can be modified without changing the tests.
* call _get_covid_county_dataset with cls so it can be overridden in subclasses, removing need to mock it
* change CanScraperBase to compute `EXPECTED_FIELDS` from `VARIABLES` with some funky metaclass stuff.
* add some unit tests checking the constants in subclasses of CanScraperBase
Tests pass except for tests/libs/generate_api_v2_test.py::test_build_summary_for_fips, which is expected to be fixed by https://github.com/covid-projections/covid-data-model/pull/988
> can_scraper_helpers_test using make_dataset

- libs/datasets/timeseries.py
This PR makes it easier to unstack a DataFrame with variable names in the columns, which I'm planning to use to add demographic buckets to MultiRegionDataset.
> Fix timeseries column axis name in wide var DataFrames

- libs/dataclass_utils.py
- libs/datasets/data_source.py
- libs/datasets/taglib.py
- tests/combined_dataset_test.py
- tests/libs/api_v2_pipeline_test.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
- tests/test_helpers.py
I noticed that when importing more data `data update`, which I run a lot, slowed down a lot. `py-spy` pointed to creation of `Source` objects as lots of the time. This PR reduces `time pytest tests/libs/datasets/data_source_test.py::test_state_providers_smoke_test` from 2 minutes to 45 seconds.
Clean lint errors that got in with some recent commits.
> Faster Source creation

- libs/datasets/data_source.py
- libs/datasets/sources/cdc_testing_dataset.py
- tests/libs/datasets/sources/cdc_testing_dataset_test.py
This PR
* Removes `transform_data(cls, data: pd.DataFrame) -> pd.DataFrame` which was only used by CDCTesting, replacing it with make_dataset override, which is used by other DataSource subclasses. This simplifies changes to CanScraperBase, making it easier to add demographic buckets
* Changes test from parsing hard-coded CSV to using `test_helpers.build_default_region_dataset`
`./run.py data update` reproduces the same output
> Remove CanScraperBase.transform

- libs/datasets/sources/cdc_testing_dataset.py
- tests/libs/datasets/sources/cdc_testing_dataset_test.py
- tests/libs/metrics/test_positivity_test.py
This PR makes https://github.com/covid-projections/covid-data-model/pull/1002 smaller and is part of https://trello.com/c/lvRFxC5y/932-get-dei-vaccination-data-into-api
* refactors CDCTesting data_source so all the interesting logic is easy to test
* tests all the interesting logic of CDCTesting
* changes tests/libs/metrics/test_positivity_test.py to be consistent with other tests using `None` in timeseries passed to build_default_region_dataset
> CDCTesting test coverage improvement, use None in test time-series

- libs/datasets/timeseries.py
- tests/libs/datasets/data_source_test.py
- tests/libs/datasets/timeseries_test.py
- tests/libs/generate_api_v2_test.py
This will fix the breakage in the data update by making sure that all data has an aggregate level.
> Adding aggregate level to dataset if not included

- tests/libs/generate_api_v2_test.py
> fix generate_api_v2_test.py::test_build_summary_for_fips after newDeaths was added

- libs/datasets/sources/can_scraper_helpers.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
This PR follows up on https://github.com/covid-projections/covid-data-model/pull/987 and https://covidactnow.slack.com/archives/C015V4JS952/p1615408720113400 
`./run.py data update` produced identical `data/multiregion-wide-dates.csv`
> change can_scraper_helpers BadLocationId warning to raises

- dash_app/dashboard.py
- libs/datasets/ca_vaccination_backfill.py
- libs/datasets/new_cases_and_deaths.py
- libs/datasets/sources/zeros_filter.py
- libs/datasets/tail_filter.py
- libs/datasets/timeseries.py
- libs/datasets/vaccine_backfills.py
- libs/metrics/test_positivity.py
- tests/libs/datasets/timeseries_test.py
This PR is part of https://trello.com/c/lvRFxC5y/932-get-dei-vaccination-data-into-api. It makes bucketed and not bucketed more explicit.
* Changes method `timeseries_wide_dates()` to property `timeseries_not_bucketed_wide_dates` and adds `timeseries_bucketed_wide_dates` which will gradually replace it.
* Changes `test_timeseries_long` to use test_helpers instead of CSV in a string to create input dataset
* Removes unused `_timeseries_long`
> Time-series bucketed long

- dash_app/dashboard.py
- libs/datasets/tail_filter.py
- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
This PR is part of https://trello.com/c/lvRFxC5y/932-get-dei-vaccination-data-into-api.
* Changes `timeseries_bucketed_wide_dates` to return bucket as inner/right index level to be more consistent with idea that a set of time-series form a distribution within one metric/variable.
* Changes `read_from_pointer` to load the bucket if the column is present and assume `all` if not
* Changes `timeseries_rows` (which is called by `write_to_dataset_pointer`) to include bucket in the index
`./run.py data update` adds demographic_bucket column always containing "all". 
Confirmed that nothing else changed with
```
mv data/multiregion-wide-dates.csv data/multiregion-wide-dates-demo.csv
csvcut -C demographic_bucket data/multiregion-wide-dates-demo.csv | perl -np -e 's/,+$//' > …
```
> add support for reading and writing with bucket.

- cli/data.py
- libs/datasets/data_source.py
- libs/datasets/sources/zeros_filter.py
- libs/datasets/timeseries.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
- tests/libs/datasets/timeseries_test.py
- tests/libs/datasets/zeros_filter_test.py
* Prints some really ugly but useful stats about buckets at a bunch of places down the pipeline so I can see where they get dropped
* Fixes zeros filter to preserve buckets
* Changes `CanScraperBase` to include buckets beyond "all"
Example output:
```
Dataset TailFilter:
all   not_all
tests         1581211.0       0.0
hospitals      545252.0       0.0
cases_deaths  2273802.0       0.0
vaccines       185519.0  133777.0
```
> print bucket stats, fix zeros filter

- libs/datasets/vaccine_backfills.py
- tests/libs/datasets/vaccine_backfill_test.py
> adds vaccine_backfills bucket support

- libs/datasets/ca_vaccination_backfill.py
- tests/libs/datasets/ca_vaccination_backfill_test.py
> preserve buckets in ca_vaccination_backfill

- cli/data.py
- libs/datasets/new_cases_and_deaths.py
- libs/datasets/timeseries.py
- tests/libs/datasets/new_cases_and_deaths_test.py
- tests/libs/datasets/timeseries_test.py
* join_columns bucket support
* new_cases_and_deaths bucket support
* data.py bucket stat printing at more steps
> join_columns and new_cases with buckets

- libs/datasets/region_aggregation.py
- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
* Adds bucket support in `MultiRegionDataset.append_regions`, `drop_column_if_present`, `drop_stale_timeseries bucket`, `get_locations_subset`, `remove_locations`
* clarify scale_factors axis in region_aggregation with an assert
Ran `./run.py data update` then `git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv` to see that this adds a bunch of rows for variables vaccinations_completed, vaccinations_initiated,vaccines_administered with buckets such as  age:16-49 or race:unknown;ethnicity:hispanic (and a bunch more buckets) for counties in PA and TX. I don't see any other changes in the data.
> More bucket support in MultiRegionDataset methods

- data/multiregion-wide-dates.csv
- data/multiregion.json
- libs/datasets/data_source.py
- tests/libs/datasets/data_source_test.py
- tests/libs/datasets/timeseries_test.py
- tests/test_helpers.py
* Expands `DataSource._check_data` to truncate data from before 2020-01-01 and rename it to `_check_and_removed_unexpected_data`
* Expands DataSource.IGNORED_FIELDS to include more fields that are okay to be ignored now that geo data is loaded from elsewhere
* Adds `test_helpers.read_csv_str` to produce data for testing _check_data and use it in timeseries_test
This PR includes an updated `multiregion-wide-dates.csv` because the current main has data going back to 1970 and uses > 9GB of memory.
Ran `./run.py data update`, saw the log output of data being dropped and checked for sensible header row in `data/multiregion-wide-dates.csv`
> Truncate old dates. Add test_helpers.read_csv_str.

- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
https://sentry.io/organizations/covidactnow/issues/2295671173/?project=5203044&referrer=slack was a bit surprising to me, but it turns out that because latest is stored in a wide variables way, it somewhat pollutes the bucket name space.
The proper fix is to make `_timeseries_bucketed_latest_values` work from wide dates, but this is a quicker fix that should be alright for now.
> Fix case where values for a bucket dont exist

- .github/workflows/deploy_aws_api_infrastructure_dev.yml
- api/awsauth/awsauth/auth_app.py
- api/awsauth/end_to_end_test.py
- api/awsauth/tools/deploy-api-infrastructure.sh
- api/awsauth/unit_test.py
This adds in a couple sanity checks before and after the lambda deploy.
I think this could potentially belong in a separate step, but because they are lightweight and broad checks, it doesn't feel like it steps on the toes of other types of testing.  
Checks added:
* Unit test to load config object - this protects against a bad .env file
* Simple request checking that api endpoints work
> Add additional checks on API infra deploy

- dash_app/dashboard.py
- libs/qa/timeseries_stats.py
- tests/libs/qa/timeseries_states_test.py
* Replaces the DataFrame object per stat in AggregatedStats with a single DataFrame with a column per stat, moving the CommonField variable to level 1 of the index. This simplifies methods `aggregate` and `subset_variables` and will make it easier to add other stats and support buckets.
* Adds some clunky but functional tests of timeseries_stats behavior called by the dashboard code
* Adds some `__post_init__` assert checks that document and enforce the expected structure of the stats DataFrame
> timeseries_stats single DataFrame

- api/awsauth/awsauth/auth_app.py
- api/awsauth/awsauth/config.py
- api/awsauth/awsauth/hubspot_client.py
This is a first step to improving the signup form - we will be using a hubspot form to pass additional signup data through.  
This will then be added to the contact created in hubspot.
As we add in more data that will be passed up through the sign up form, we can add more properties here
> Submit hubspot form instead of normal contact creation

- api/awsauth/awsauth/auth_app.py
- api/awsauth/awsauth/hubspot_client.py
- api/docs/src/components/SignupForm.jsx
This lets us capture the hubspot token cookie and pass to form submission.  
Also adds in a bit of refactoring - when the more complicated reg form is added there will be a separate endpoint for retrieving an existing token.  This breaks up the `_get_api_key` and `_create_new_user` functions and adds a small class to parse/handle errors for input
> Adding hubspot token to form

- libs/datasets/manual_filter.py
- tests/libs/datasets/manual_filter_test.py
Unblock CASES and DEATHS that were blocked for https://trello.com/c/aj7ep7S7/1130-3-utah-counties-tricounty now that https://github.com/nytimes/covid-19-data/issues/560 is addressed.
`./run.py data update` and `git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv` confirms that only cases and deaths for these 3 counties change and they are different now.
> remove block for UT TriCounty

- cli/data.py
This PR finishes https://trello.com/c/EyISOtVY/623-usa-data-aggregation-in-pipeline-doesnt-work
`./run.py data update` and `git status`, `git difftool` showed that data/multiregion-wide-dates.csv and data/multiregion-status.csv had iso1:us data added and nothing else changed.
`python pyseir/cli.py build-all --generate-api-v2 --location-id-matches 'iso1:us$'` ran without error on my laptop but didn't output any API data. Getting it in the API is https://trello.com/c/dckJRBsA/574-add-usa-aggregation-to-api.
> data update --aggregate-to-country by default

- libs/datasets/combined_datasets.py
- libs/datasets/sources/hhs_hospital_dataset.py
- tests/libs/datasets/sources/hhs_hospital_dataset_test.py
Tested via `./run.py data update` and `git difftool`.  The resulting multiregion dataset files were identical except for some rounding errors and the (desired) inclusion of source url / name information.
> Migrate hhs hospital importer to covid-data-model.

- libs/datasets/combined_datasets.py
- libs/datasets/manual_filter.py
- tests/libs/datasets/combined_dataset_utils_test.py
- tests/libs/datasets/data_source_test.py
- tests/libs/datasets/manual_filter_test.py
- tests/libs/datasets/taglib_test.py
- tests/test_helpers.py
This PR was originally motivated by  https://github.com/covid-projections/covid-data-model/pull/1065 but wasn't used to resolve it.
* adds manual_filter support for field_group
* adds datasource_regions manual_filter
* Unrelated fix for tests/libs/datasets/data_source_test.py::test_can_scraper_class_expected_fields_set by changing get_concrete_subclasses to get_concrete_subclasses_not_in_tests, exempting test subclasses from checks
> More uses of manual_filter. Ignore tests when checking subclasses.

- dash_app/dashboard.py
Manually tested. To get faster dashboard reloads I used a subset of our data with
```
cp tests/data/test-combined-wide-dates.csv data/multiregion-wide-dates.csv
cp tests/data/test-combined-static.csv data/multiregion-static.csv
```
> Fewer dashboard tables, pivot table help and defaults

- libs/datasets/combined_datasets.py
This PR addresses https://trello.com/c/Qrgw8AR9/1228-switch-iowa-cases-back-to-nyt-instead-of-usa-facts-igor-says-its-fixed by undoing some of https://github.com/covid-projections/covid-data-model/pull/982
> remove exclude IA counties from NYT data

- cli/data.py
I've been using a subset of data created with 
```
./run.py data update-test-combined-data --no-truncate-dates --state SD
cp tests/data/test-combined-wide-dates.csv data/multiregion-wide-dates.csv
cp tests/data/test-combined-static.csv data/multiregion-static.csv
```
to browse SD data while working on https://trello.com/c/KdcwKHwK/1241-several-south-dakota-counties-have-fully
> add update_test_combined_data command line options

- libs/datasets/taglib.py
- libs/datasets/timeseries.py
- libs/datasets/vaccine_backfills.py
- tests/libs/datasets/timeseries_test.py
- tests/libs/datasets/vaccine_backfill_test.py
This PR is part of https://trello.com/c/jeoMFnbb/1243-revisit-backfillvaccinationinitiated
* Adds taglib.Derived that for now has no attributes so is encoded as an empty JSON `"{}"`
* Adds `MultiRegionDataset.add_tag_to_subset` making it easy to add a tag to a subset of time series
* Changes how backfill_vaccination_initiated merges calculated and existing time series without changing behavior
Ran `./run.py data update` and checked `git difftool -t vimdiff --no-prompt main -- data/multiregion-annotations.csv` only adds a column.
05eecac asserted that the old and new way of merging the backfill produced the same output. This worked with the current combined data.
> tag vaccine backfill as derived

- libs/datasets/timeseries.py
- tests/libs/datasets/custom_aggregations_test.py
- tests/libs/datasets/timeseries_test.py
This PR is part of https://trello.com/c/f27O08ea/1266-make-it-possible-to-block-in-the-backend-using-the-cms and helps https://github.com/covid-projections/covid-data-model/pull/1080
* Adds support for MultiRegionDataset.tag without timeseries values
* (unrelated) Removes unused MultiRegionDataset.timeseries_regions
* (unrelated) Removes one use of deprecated MultiRegionDataset.provenance
> Allow MultiRegionDataset.tag without timeseries

- cli/data.py
- libs/datasets/manual_filter.py
This PR is for https://trello.com/c/HdAKfp49/1139-disabled-all-ok-counties-except-2-no-longer-reporting-cases
* Removes OK county manual_filter
* Stop calling manual_filter run during data update because https://github.com/covid-projections/covid-data-model/pull/1080 will bring it back
Ran `./run.py data update` and looked at `git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv`. There I saw
* known_issues annotation column removed
* us-ok counties cases and deaths rows have new cumulative values, but only updated ~weekly
* us-ok counties new_cases and new_deaths have lots of zeros, for example `iso1:us#iso2:us-ok#fips:40019,new_cases` newest dates first `19,0,0,0,0,0,0,43,0,0,0,0,0,0,69,0,0,0,0,0,0`. This is unchanged from main because the manual filter (that …
> Rm OK county cases, last manual filter

- libs/datasets/ca_vaccination_backfill.py
- libs/datasets/combined_datasets.py
- libs/datasets/custom_aggregations.py
- libs/datasets/manual_filter.py
- libs/datasets/taglib.py
- libs/datasets/timeseries.py
- libs/pipeline.py
- tests/libs/datasets/combined_dataset_utils_test.py
- tests/libs/datasets/manual_filter_test.py
- tests/libs/datasets/timeseries_test.py
- tests/test_helpers.py
This PR is part of https://trello.com/c/f27O08ea/1266-make-it-possible-to-block-in-the-backend-using-the-cms
Most of these changes are done to simplify drop_observations because https://github.com/covid-projections/covid-data-model/pull/1080 uses different subsets of the code.
* changes manual_filter config to use a pydantic model instead of unstructured JSON
* replaces MultiRegionDataset.remove_regions with MultiRegionDataset.partition_by_region
* adds MultiRegionDataset.replace_timeseries_wide_dates which is used in the new manual filter code and replaces some funky use of dataclasses.replace in ca_vaccination_backfill.py
* adds RegionMask comments
* changes KnownIssue.date to a datetime instead of panda timestamp, for better compatibility with pydantic
`/run.py data update` reproduced …
> Refactor drop_observations

- data/geo-data.csv
- libs/datasets/sources/can_scraper_helpers.py
This unblocks our data updates.
Tested via: `./run.py data update`
I think we're squashing the incoming US-level data so it didn't actually show up in the output, but at least the pipeline is unblocked.
FYI- This is the diff on geo-data.csv since github doesn't show it:
> Wire up US to FIPS 0.

- dash_app/dashboard.py
- libs/qa/timeseries_stats.py
- tests/libs/qa/timeseries_stats_test.py
* Moves the non-numeric column source_type_set out of Aggregate.stats so that `stats.groupby(...).sum()` does what I'd expect
* Moves creation of the list of data for the pivottable into Aggregate to keep logic around stats and source_type in one class.
* Fixes `PerTimeseries.__post_init__` to call super class, I thought this was already happening
* Factor out PerTimeseries._subset
* Change PerTimeseries.aggregate to accept any number of fields so it can be used by stats_for_locations, factoring out a call to stats.groupby
> move non-numeric column out of PerTimeseries.stats

- libs/datasets/vaccine_backfills.py
- tests/libs/datasets/vaccine_backfill_test.py
This PR fixes a bug in `backfill_vaccination_initiated` that I noticed while working on https://github.com/covid-projections/covid-data-model/pull/1094
`computed_initiated` was being kept even when it was all NA for a location+bucket. This happens when one or both of administered and completed were all NA. The bug cause combined datasets to include a row with a derived tag but no real values. The fix is changing dropna axis param to `0, or ‘index’ : Drop rows which contain missing values.` (from DataFrame.dropna docs).
```
git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv
```
shows 2533 dropped empty `vaccinations_initiated` for various buckets that all have derived tag `{}`.
> backfill_vaccination_initiated incorrectly added empty time series

- libs/datasets/taglib.py
- libs/datasets/timeseries.py
- libs/datasets/vaccine_backfills.py
- libs/metrics/test_positivity.py
- libs/qa/timeseries_stats.py
- tests/libs/datasets/timeseries_test.py
- tests/libs/datasets/vaccine_backfill_test.py
This is some more cleanup associated with https://github.com/covid-projections/covid-data-model/pull/1094
* Adds tag parameter `Derived.f` to save the function name, useful now that we're adding that tag to the same field from multiple places.
* Replaces some direct access to `MultiRegionDataset.timeseries_bucketed_wide_dates` with new function `get_timeseries_bucketed_wide_dates` that returns one field and similarly for `timeseries_not_bucketed_wide_dates`.
* Replaces some calls to Index.get_level_values with Index.unique where a copy of the value per index entry isn't needed. See https://stackoverflow.com/a/50364903
```
git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv
```
shows the same diff as …
> MultiRegionDataset.get_timeseries_bucketed_wide_dates and friends

- cli/data.py
- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
This PR is part of https://trello.com/c/sJDKzKIU/1302-make-usa-aggregation-use-incoming-usa-data-if-it-exists-rather-than-aggregate-the-states
* re-write drop_regions_without_population to not depend on MultiRegionDataset.static. Country data was silently dropped because the country did not appear in 'static'.
* Extend print_stats to breakdown by level so I can see where the country data is being dropped
* print_stats at a few more stages of data update
`./run.py data update` reproduced identical output to main.
> drop_regions_without_population fix for country data

- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
- tests/test_helpers.py
This PR is part of https://trello.com/c/sJDKzKIU/1302-make-usa-aggregation-use-incoming-usa-data
- test_helpers.build_dataset support for empty timeseries.
- change MultiRegionDataset.join_columns to support joining static data.
- add __post_init__ check for static.columns.is_unique to verify that the structure is as expected
> MultiRegionDataset.join_columns to support joining static data.

- libs/datasets/combined_datasets.py
This PR addresses https://trello.com/c/JQh3iWkJ/1344-add-cdc-us-country-level-data-without-being-overwritten-by-aggregation
`./run.py data update` and `git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv` shows 4 time series changed, all country level vaccine data gained the CDC source tag.
> add CDC country vaccine numbers

- dash_app/dashboard.py
This PR is part of https://trello.com/c/1p0uTkYH/1300-pipeline-generate-csv-of-blocked-metrics-and-make-it-easy-for-data-dashboard-to-read-it
* Moves part of dashboard page that displays the data to be returned by a callback instead of being set to the app layout. This is based on https://dash.plotly.com/urls
* Adds an enum for dash component ids and starts to replace hard-coded strings sprinkled around the dash python code.
For fast testing I ran
```
cp tests/data/test-combined-static.csv data/multiregion-static.csv ; cp tests/data/test-combined-wide-dates.csv data/multiregion-wide-dates.csv 
python ./run_dash.py 
```
> return dash page content from callback

- cli/data.py
- data/manual_filter_removed-static.csv
- data/manual_filter_removed-wide-dates.csv
- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
This PR addresses https://trello.com/c/1p0uTkYH/1300-pipeline-generate-csv-of-blocked-metrics-and-make-it-easy-for-data-dashboard-to-read-it
* Adds `MultiRegionDataset.static_long`, the static DataFrame restructured into a Series
* Adds `MultiRegionDatasetDiff` to calculate the diff between two `MultiRegionDataset`
* Uses `MultiRegionDatasetDiff` to record timeseries removed by the manual filter.
* Adds some more asserts and comments related to `MultiRegionDataset.static` that I noticed while working on this change.
> calculate manual_filter diff using MultiRegionDatasetDelta

- libs/datasets/timeseries.py
- tests/libs/datasets/data_source_test.py
- tests/libs/datasets/timeseries_test.py
This PR addresses https://trello.com/c/2hfcOmg2/1358-fix-cms-testing-import-and-prevent-future-bad-fips-breaking-data-update
With covid-data-public checked out without Michael's fix (for example at 41f54e8) and without this change `./run.py data update` crashes.
```
2021-05-17T22:23:45.414578Z Exception reached __main__     [root] exc_info=(<class 'ValueError'>, ValueError("Problem with <class 'libs.datasets.sources.cms_testing_dataset.CMSTestingDataset'>"), <traceback object at 0x7f73015e3c30>)
Traceback (most recent call last):
File "/home/thecap/projects/covid-data-model/cli/data.py", line 355, in _load_dataset
dataset = data_source_cls.make_dataset()
File "/home/thecap/projects/covid-data-model/libs/datasets/data_source.py", line 119, in make_dataset
return …
```
> drop instead of raise bad fips

- Makefile
This PR addresses https://trello.com/c/z2ZSJIoP/1363-fix-covid-data-model-tests-failing-on-server-only with a quick hack fix. https://trello.com/c/hCeBoMlZ/1369-get-tests-running-in-parallel-on-the-big-server is a card to debug and revert this.
> change Make unittest to -n 1

- cli/data.py
- libs/datasets/taglib.py
- libs/datasets/timeseries.py
- tests/libs/datasets/timeseries_test.py
- tests/test_helpers.py
This PR addresses https://trello.com/c/UKqdcj0z/1345-pipeline-block-data-for-future-dates
* Adds function `timeseries.drop_observations(..., after=)` and tag `drop_future_observation` to record where it did something
* Use this function to drop data that is more recent than today, UTC
* Clean up print_stats calls so "combined" is right after the combined data is produced and adding "manual filter" stats
Running `./run.py data update` with covid-data-public manually tweaked to have a date in the future.
> add drop_observations after today UTC

- libs/datasets/manual_filter.py
- libs/datasets/taglib.py
- tests/libs/datasets/manual_filter_test.py
- tests/libs/datasets/taglib_test.py
This PR addresses a TODO I notice while working on https://trello.com/c/weIWXUgV/1353-add-enddate-to-backend-metric-blocking
> fix TODO disclaimer -> public_note in taglib

- dash_app/dashboard.py
This is a quick kludge to make viewing blocked data easier.
* call new_cases_and_deaths.add_new_cases after loading manual filtered data
> dash: add new cases in view of manually filtered data

- pyseir/rt/infer_rt.py
This PR addresses issue https://trello.com/c/JzkA9Q51/1366-can-auto-pilot-what-to-do-with-infection-rate.
The current implementation of our Infection Rate is sensitive to places with consistent low case numbers. In some cases, this will cause a systematic error that makes the metric appear to be very high and growing. Right now this error is only seen in locations that are small enough to have on the order of 1s of cases over the last couple weeks.
We our updating our model to be more clear about our uncertainty at very low cases numbers.
We decided to choose a threshold number of smoothed daily cases. Below that threshold, we say "this is too low to confidently have informed priors about the future infection rate" with the consequence that we will use the default priors to restart the …
> Improve Small N Infection Rate Performance

- tests/libs/metrics/test_positivity_test.py
- tests/test_helpers.py
I ran into deprecated check_less_precise when upgrading to pandas 1.2. This removes use of it, which works in our current pandas 1.0 and 1.2. Also removes one use of low_memory which also caused a problem in 1.2.
> remove check_less_precise, deprecated in pandas 1.1

- libs/datasets/timeseries.py
- libs/datasets/vaccine_backfills.py
This PR is part of https://trello.com/c/e0PtnB7y/489-tech-debt-upgrade-to-python-39
I'm replacing is_all_dates with explicit check for DatetimeIndex because that's what we want in the DataFrame so it seems cleaner than checking the string index.inferred_type.
Changes in vaccine_backfills.py are to preserve the DatetimeIndex that was removed when adding a column temporarily.
> fix for FutureWarning: Index.is_all_dates is deprecated

- libs/datasets/timeseries.py
- tests/dataset_utils_test.py
This PR is part of https://trello.com/c/e0PtnB7y/489-tech-debt-upgrade-to-python-39
* fix for 'ValueError: zero-size array to reduction operation maximum which has no identity' when .loc[[key]] isn't found. This didn't raise in pandas 1.0, does in 1.2
* fix cached_property to work with 3.7 or 3.9.
> Fix for ValueError: zero-size array

- .github/workflows/label_api_snapshot.yml
- tools/label-api.sh
This way if we ever need to revert an API snapshot, we can do it via the github UI...
Also hardcoded the label to "latest" since we don't need that flexibility.
> Convert label_api_snapshot.yml to workflow_dispatch.

- libs/metrics/top_level_metrics.py
- tests/libs/metrics/top_level_metrics_test.py
This fixes the Arkansas issue we looked at this morning (as well as a number of other cases where states/counties were on a metric threshold).
I verified that the generated summary file on the frontend (where we already were doing this kind of rounding) was unaffected except:
1. As desired, risk levels were fixed when a rounded metric value ended up on a metric threshold.
2. JavaScript and Python round slightly differently when the value ends in a `5` (e.g. `0.115` rounds to `0.12` in JavaScript but `0.11` in Python).
Also worth noting that the resulting .timeseries.json API endpoints are ~35% smaller.
> Round metric values.

- Makefile
- tests/libs/datasets/data_source_test.py
`test_state_providers_smoke_test` started crashing even without parallelization.  I suspect it's running out of memory.  Disabling it.
> Disable crashing test.

- data/region-overrides.json
This PR adds a disclaimer/public_note to 6 MO counties following up on https://trello.com/c/6roEMYkZ/1020-switch-to-usa-facts-for-6-mo-counties-nyt-is-under-reporting-kc-joplin-data
The note is added to `cases`. It is not added to `new_cases` because `new_cases_and_deaths` runs after `manual_filter` and doesn't copy tags. It isn't added to `deaths` or `new_deaths` because they aren't in `_METRIC_TO_FIELDS`.
`./run.py data update` and `git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv` shows only changes described above.
> add disclaimer/public_note to 6 MO counties

- libs/datasets/combined_datasets.py
This PR addresses https://trello.com/c/0nVivEMt/1435-fix-florida-data-scraper
```
git difftool -t vimdiff main -- data/multiregion-wide-dates.csv
```
shows some CBSA dropping vaccines_administered and gaining vaccinations_completed, vaccinations_initiated for many days in most recent ~2 weeks.  FL counties lost vaccines_administered and vaccinations_initiated demographic breakdowns and has only vaccinations_completed age 18+, 65+, all buckets but gained a much more complete timeseries.
> Exclude FL counties from vaccine fields when reading from CAN scraper state providers

- libs/datasets/combined_datasets.py
- libs/metrics/top_level_metric_risk_levels.py
- tests/libs/metrics/top_level_metric_risk_levels_test.py
This PR addresses https://trello.com/c/trOrDzSb/1439-api-overall-risk-level-doesnt-match-website-when-cases-are-unknown
> unknown top level risk when cases is unknown

- cli/data.py
- libs/datasets/combined_datasets.py
This PR adds data collected by https://github.com/covid-projections/can-scrapers/pull/318 to the combined data, addressing https://trello.com/c/IEXT5YRn/1423-blocked-5-26-onward-nebraska-stopped-reporting-cases-at-county-level
> Get NE county cases from state provider. add --no-print-stats

- data/region-overrides.json
Adds disclaimer copied from https://twitter.com/TexasDSHS/status/1407806450135666699 though it is unclear exactly what dates this applies to and if it makes sense to leave it up for those dates in the future (even though the FE doesn't support date ranges) or take it down in about a week.
> add disclaimer copied from Texas DSHS

- libs/datasets/vaccine_backfills.py
- tests/libs/datasets/vaccine_backfill_test.py
Previously we wouldn't estimate 1st dose data from completed if there was any
1st dose data at all (even if it was really stale).
With this change, we look back 16 days and if there's no 1st dose data in that
span, then we estimate 1st dose from completed. This is necessary since some
of the new CDC timeseries data has stale 1st dose data for some reason and we
want to go ahead and replace it with estimated data so we can use it on the website.
Tested via: `./run.py data update`.  Data didn't change (we don't have any providers with up-to-date complete data but stale 1st dose data presently).  
cc/ @smcclure17
> Estimate 1st dose data if it's been missing recently.

- api/can_api_v2_definition.py
- api/docs/docs/updates.md
- api/docs/open_api_schema.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- libs/build_api_v2.py
- libs/metrics/cdc_transmission_levels.py
- libs/pipelines/api_v2_pipeline.py
- libs/pipelines/csv_column_ordering.py
- tests/libs/build_api_v2_test.py
- tests/libs/metrics/cdc_transmission_level_test.py
This adds the latest cdc transmission level to the json adn csv output.
Note that this does not add to the timeseries data.  it's not a ton more work, but figured this was the minimum steps to get it working.
> Add cdc transmission levels

- libs/datasets/vaccine_backfills.py
- tests/libs/datasets/vaccine_backfill_test.py
Reduces the number of days until the 1+ dose estimation kicks in so that estimation will start immediately once the data would go stale. This should prevent counties that are switching to estimation from going gray/stale for one day in between.
> reduced vaccine estimation backfill threshold by one day

- api/can_api_v2_definition.py
- api/docs/open_api_schema.json
- api/schemas_v2/AggregateFlattenedTimeseries.json
- api/schemas_v2/AggregateRegionSummary.json
- api/schemas_v2/AggregateRegionSummaryWithTimeseries.json
- api/schemas_v2/CdcTransmissionLevelRow.json
- api/schemas_v2/CdcTransmissionLevelTimeseriesRow.json
- api/schemas_v2/RegionSummary.json
- api/schemas_v2/RegionSummaryWithTimeseries.json
- api/schemas_v2/RegionTimeseriesRowWithHeader.json
- libs/build_api_v2.py
- libs/metrics/cdc_transmission_levels.py
- libs/pipelines/api_v2_pipeline.py
- libs/pipelines/csv_column_ordering.py
- tests/libs/build_api_v2_test.py
- tests/libs/metrics/cdc_transmission_level_test.py
This adds cdcTransmissionLevel timeseries data to the JSON and CSV api endpoints.  In JSON it shows up as:
```
"cdcTransmissionLevelTimeseries": [
{
"date": "2020-01-14"
"cdcTransmissionLevel": 0,
},
...
}
```
In the CSV timeseries files it shows up as a new `csvTransmissionLevel` column.
In general I modeled the code off of the existing code for `riskLevelsTimeseries`.
Snapshot 2249 was built with these changes. Example endpoints with the new data:
* https://data.covidactnow.org/snapshot/2249/v2/state/WA.timeseries.json
* https://data.covidactnow.org/snapshot/2249/v2/state/WA.timeseries.csv
> Add cdcTransmissionLevel timeseries data to API.

- Makefile
- tests/infer_rt_test.py
Get our unit tests passing again by:
1. Disabling parallel running (see comment).
2. Disabling the tests failing due to Louisiana r(t) being broken (see https://trello.com/c/7Me3N5N4/).
> Fix unit tests.

- libs/datasets/combined_datasets.py
This removes ND from the exclusion list such that the pipeline will now use CDC data. 
It looks like the ND scraper was previously collecting `% of 12+ population vaccinated` as `% of total population vaccinated` causing our data to be inflated. 
For example Cass County has a population of 185,181,  and is [reporting 104,220 people with at least one dose](https://www.health.nd.gov/covid19vaccine/dashboard): `104,220 / 185,181 = 0.56`, which fairly closely lines up with the [CDC's reported value](https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh/data) of 54%. Previously we were reporting over 60% (we we're multiplying the `12 and older at least one dose` percentage by the total population). 
I think it makes sense to:
- delete the incorrect …
> remove ND from CDC exclusion list

- libs/datasets/combined_datasets.py
We currently expose licensed_beds from CovidCareMap in our API (as hospitalBeds.capacity) even though we know this data isn't very high-quality. We'd like to switch to using staffed_beds from the HHS hospital data (and get rid of CovidCareMap), but we currently don't include it in our combined dataset files.
This PR fixes that.
> Add STAFFED_BEDS to combined datasets.

- tests/data/test-combined-static.csv
- tests/data/test-combined-wide-dates.csv
- tests/libs/build_api_v2_test.py
- tests/libs/datasets/timeseries_test.py
This is the result of running `./run.py data update-test-combined-data` to update our test combined datasets file (basically just a subset of the full one to make it easier for tests to load) now that we have staffed_beds in it.  But getting new data required me to update some tests.
> Regenerate test combined datasets data (and fix tests).

- libs/pipelines/api_v2_pipeline.py
- libs/pipelines/csv_column_ordering.py
- tests/libs/csv_column_names_test.py
Addresses the concern a couple API users have expressed about "unused" API columns being duplicated.
> Relabel unused columns to be unique.

- libs/datasets/combined_datasets.py
NE has restarted reporting county-level case data. This removes the NE filter on the NYT cases dataset, overriding the State Scraper source. 
USAFacts did not appear to have the case data, so I've left the filter in place for that dataset
> remove NE cases from NYT exclusion list

- cli/data.py
- libs/datasets/nytimes_anomalies.py
- tests/libs/datasets/nytimes_anomalies_test.py
Uses the NYT anomalies dataset to filter our new cases and new deaths timeseries, removing data points that NYT has flagged as anomalies.  This is in addition to our existing outlier detection but may give us some future leeway to remove outlier detection or make it less sensitive.
The net effect (given our outlier detection) is fairly small but detectable.
Compare links:
* States: https://covidactnow.org/internal/compare?left=2361&locations=1&metric=5&right=2362&sort=2
* Top Counties: https://covidactnow.org/internal/compare?left=2361&locations=2&metric=5&right=2362&sort=2
FWIW- It can be a bit easier to pick out the deltas if you actually open the link in two tabs, but swap left/right in one of the tabs and then you can switch back and forth between the tags to see them overlaid.
> Use NYT anomalies to filter daily new cases and deaths.

- libs/datasets/combined_datasets.py
The NE case scraper seems to be back after being down mid and late last week, but since NYT now has true county-level case data I think it makes sense to use that. 
This leaves the region mask and the filtered USA Facts source in the code, as it seems this might happen again in the future. 
Let me know if you'd like to handle this in any other way, or if you have any suggestions/changes in mind!
Also, not sure why the lint/formatting is failing, but I can look into it
> remove NE county region mask from NYT and USA Facts sources

- libs/datasets/combined_datasets.py
See https://covid-projections-git-bump-snapshot-2560-1471-covidactnow.vercel.app/internal/compare/?left=2558&locations=NE&metric=6&right=2560&sort=3 for a snapshot built with these changes.
> Block CDC 1st dose data for NE counties.

- tools/push-data-update.sh
Should avoid some of the recent failures.
> Make data update pull right before pushing in case other changes were committed.

- libs/metrics/top_level_metrics.py
If the timeseries is all zeros then `last_nonzero_index` is `None`, causing the comparison on line 164 to fail. 
This change means that we will never truncate the trailing zeros for an all-zero series (even if the series is shorter than `stall_length`)
this addresses the sentry error: https://sentry.io/organizations/covidactnow/issues/2907283165/?environment=Environment.PRODUCTION&project=5203044&referrer=alert_email
> Don't remove trailing zeros on an all-zero series

- .github/workflows/update_repo_datasets.yml
The scheduled runs are not triggering the API build because `trigger_api_build` is only defined using `workflow_dispatch`. This should default to `true` if no `trigger_api_build` input exists (according to https://github.community/t/how-can-you-use-expressions-as-the-workflow-dispatch-input-default/141454/2)
Not sure of a great way to test this, as I'm not sure if scheduled runs will be triggered on non-main branches. I'll take a quick look into this
> trigger API build on scheduled Update combined datasets actions

- libs/datasets/combined_datasets.py
- scripts/can_raw_location_page_urls.py
Add data to allow state-provided booster data to flow through the pipeline.
Necessary to have CA state-provided data surfaced on the website. Related to https://github.com/covid-projections/can-scrapers/pull/404
> Add state-provided backup boosters source

- libs/datasets/combined_datasets.py
Block CDC data so that state-dashboard data can flow through for North Carolina counties.
> Block CDC datasource for NC counties

- libs/datasets/combined_datasets.py
I misinterpreted "ScraperCountyProviders" as "a source providing data for counties" instead of "a county health department source". We want to use scraper data from state health department dashboards
> Replace CANScraperCountyProviders with CANScraperStateProviders for booster data

- libs/datasets/combined_datasets.py
I believe that [`CANScraperStateProvidersWithoutFLCounties`](https://github.com/covid-projections/covid-data-model/pull/1239/files#diff-42917a247dcc7f465b77be023ee9800e3597bb2bb5dd1b09fbf1d2253a14c01bL236) should automatically include state-level data because no aggregation level was specified, so this should pick up the NC state-level data without any changes. If I'm missing something or am misunderstanding, let me know. 
Once the NC data is ingested from `can-scrapers` I'll create a test snapshot.
> Block NC state-level data from CDC vaccine dataset

- .github/workflows/update_repo_datasets.yml
Adds a `repository_dispatch` option to allow the action to be triggered by a `post` request in can-scrapers. This would replace the cron scheduler currently used (although I've kept the schedule active for now). 
I've been following the steps outlined [here](https://dev.to/rikurouvila/how-to-trigger-a-github-action-with-an-htt-request-545), and have a [PR in the works to make the trigger request in can-scrapers](https://github.com/covid-projections/can-scrapers/pull/413).
> Add repo dispatch for triggering via HTML request from can-scrapers

- data/region-overrides.json
No current issue is being addressed.
Comparing data from NYT and USAFacts, the Idaho data stagnates around January 07, but is in sync again by January 10 (sampling of Twin Falls).
Revising the disclaimer to the IDHW verbage and unblocking the data.
> unblock all of idaho

- .github/workflows/deploy_api.yml
- matplotlibrc
- run.sh
Allow API snapshots to be built on an existing `execute-model` run from a previous snapshot. 
Snapshot built on a previous model [here](https://github.com/covid-projections/covid-data-model/runs/5218915753?check_suite_focus=true).
Snapshot building off this branch without an existing model [here](https://github.com/covid-projections/covid-data-model/actions/runs/1854295934)
> Add optional run number to download execute-model results from

- .github/workflows/update_repo_datasets.yml
Remove the 3:00 AM EST Update Combined Datasets run to rely on the [runs triggered from Prefect](https://github.com/covid-projections/can-scrapers/pull/413). 
I've left the 5:00 AM run active as a backup for now, in case anything goes wrong with the Prefect triggers
> Remove the 3:00 AM EST Update Combined Datasets scheduled run

- datapublic/common_fields.py
- libs/datasets/combined_datasets.py
- libs/datasets/region_aggregation.py
- libs/datasets/sources/cdc_community_levels_dataset.py
- libs/datasets/sources/hhs_hospital_dataset.py
Pulls in hospital admissions data from HHS and CDC Community Levels from CDC from the parquet and into our combined datasets data.
Tested via `./run.py data update --state CT` and inspecting the resulting data/multiregion-wide-dates.csv file for the expected fields.
> Ingest Hospital admissions and CDC Community Levels

- .github/workflows/deploy_api.yml
- .github/workflows/update_repo_datasets.yml
`./run.py data update` accepts a `--no-refresh-datasets` option that tells it to skip fetching / combining datasources and instead re-use the checked-in `combined-raw.pkl.gz` data.  This PR exposes that option to the github action.  This can be used to save time when you just need to block data and re-build the snapshot.
I also tweaked the github actions to work with branches that have `/` in the name.
> Add option to github action to skip refreshing datasets.

- .github/workflows/deploy_api.yml
- .github/workflows/update_repo_datasets.yml
This was merged in https://github.com/covid-projections/covid-data-model/pull/1266 but I decided to revert it since I hadn't tested it end-to-end and I don't want to risk tomorrow's deploy.  I'll merge again tomorrow.
> Add option to github action to skip refreshing datasets. (#1266)

- libs/metrics/top_level_metrics.py
Alternatively, we could have locations without HSAs calculate this metric using strictly county data, but it would be confusing to track what locations are using what method.
> Fix DC and MP API endpoints

- libs/metrics/top_level_metrics.py
https://github.com/covid-projections/covid-data-model/pull/1261 Only increased the default value, but the 10-day value was still being specified when the truncation function was called, so trailing zeros we're still only being truncated for 10 days. 
Also, I think we only need to truncate 14 days not 15
> Fix case data truncation

- libs/datasets/custom_patches.py
- libs/datasets/statistical_areas.py
Demographic data was getting clobbered/removed from the `MultiregionDatasets` due to my use of `timeseries` instead of `timeseries_bucketed`. This updates the code where necessary to restore demographic data
post-fix: https://gist.githubusercontent.com/smcclure17/a50c3c6395bb37552771104b11279c8f/raw/a1ad4a60a4fd6af40d1807f26b7ec0d2d23f3a12/ca-06037.json
pre-fix: https://gist.githubusercontent.com/smcclure17/2365b842dbbb510d620453298957ce52/raw/4edb7fe774f88e8f80bfd90a8ba9a9407efb9418/ca-06037.json
> Restore demographic vaccine data

- .github/workflows/deploy_api.yml
Your instructions at https://www.dropbox.com/scl/fi/d2zuir4wx69i3uf84hb62/GitHub-Actions-Runner-on-GCE-Setup.paper were basically spot-on but I ran into one issue with fastparquet not installing successfully. This was the only way I found to get it to work. 🤷
> Manually install numpy before fastparquet.

- cli/data.py
- data/can_scrape_api_covid_us.parquet
- libs/datasets/data_source.py
- libs/datasets/sources/can_scraper_helpers.py
Tweak the data pipeline such that the scraper data parquet file does not get persisted to `data/` during each pipeline run
> Read parquet file directly from GCS

- data/multiregion-wide-dates.csv
I should have deleted this in #1296 as it has been replaced by `data/multiregion-wide-dates.csv.gz`
> Remove data/multiregion-wide-dates.csv

- libs/github_utils.py
This fixes an error I ran into when I was doing some perf testing on a new github actions runner.  When I set up the runner, I gave it a small (10GB) OS drive and a large drive for the action runner / data file stuff.  But this caused the `PYSEIR_ARTIFACT_SNAPSHOT` option to not work because it ended up trying to `rename` a file from one device to another, which apparently isn't supported.
```
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmppf9_1nlo/data/api-results-3355' -> '/mnt/data/covid-data-model/covid-data-model/api-results-3355'
```
> Fix model artifact rename to work across devices.

- api/awsauth/awsauth/auth_app.py
I've been meaning to do this for a while so we don't use up our Sentry transaction quota every month and get email notifications... 🤷
> Disable sentry performance transactions.

- .github/workflows/deploy_aws_api_infrastructure_dev.yml
- api/awsauth/serverless.yml
Fixes issue encountered in https://github.com/covid-projections/covid-data-model/runs/8100141218?check_suite_focus=true
It seems like serverless v3 broke us.  I fixed one issue, but hit a different issue, so I'm pinning at 2.72.3.
> Fix provider.region in serverless.yml and pin serverless version.

- .github/workflows/deploy_aws_api_infrastructure_dev.yml
I missed a spot where we need to pin the serverless version (for the prod deploy).
> Fix serverless version for prod deploy.

- libs/datasets/sources/can_scraper_helpers.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
Potential temporary fix for https://github.com/covid-projections/covid-data-model/actions/runs/3309895617
> Remove dupes from scraper as a temporary bandaid fix.

- libs/datasets/sources/can_scraper_helpers.py
- tests/libs/datasets/sources/can_scraper_helpers_test.py
I've:
- Reverted the database to a backup from Oct. 22nd, 2022 (before the duplicates issue began)
- Ran the HHS facility-level scraper and generated a new parquet file
- Tested an [Update Combined Datasets](https://github.com/covid-projections/covid-data-model/actions/runs/3330302904) run off of my testing branch. This made it past the point where it would previously break
> Revert duplicates hack

- libs/datasets/combined_datasets.py
Use USA Facts data for Jefferson County, KY until https://github.com/nytimes/covid-19-data/issues/692 is resolved. 
Running a test snapshot here: https://github.com/covid-projections/covid-data-model/actions/runs/3463189084
> Add Jefferson County, KY to NYT exclusion list

- .github/workflows/update_api_usage.yml
- libs/update_api_user_metrics.py
#766  Updates Hubspot to use a Bearer auth token following: https://developers.hubspot.com/docs/api/migrate-an-api-key-integration-to-a-private-app
Appears to be working per: https://app.hubspot.com/private-apps/8617439/1285491/logs/api
> Replace Hubspot API key

- .github/workflows/deploy_api.yml
- .github/workflows/update_repo_datasets.yml
I tested this approach by creating a test action in https://github.com/covid-projections/covid-data-model/pull/1337.  See an example run [here](https://github.com/covid-projections/covid-data-model/actions/runs/3635639729).
> Start / stop the GCE runner before/after use to reduce costs.

- datapublic/common_fields.py
- libs/datasets/sources/can_scraper_helpers.py
context: https://sentry.io/organizations/covidactnow/issues/3807149066/?project=5203044&referrer=slack
Issue was raised by https://github.com/covid-projections/can-scrapers/pull/448
Combined datasets run tested locally with `./run.py data update --states CT --refresh-datasets`
> Convert `location_id` column type from categorical to object

- libs/metrics/top_level_metrics.py
- libs/series_utils.py
- scripts/can_raw_location_page_urls.py
- services/data-pipeline-dashboard/Makefile
- setup.py
- tools/maybe-trigger-web-snapshot-update.sh
and other miscellaneous renamings.
The `deploy_api.yml` workflow stopped triggering the frontend workflow after the repo name change (see #notifications-daily-deploys in Slack)
> Point frontend snapshot trigger to renamed repository

- .github/workflows/update_repo_datasets.yml
Compute Engine is our biggest GCP costs so trying to reduce unnecessary runs.  This will also reduce our S3 growth in AWS.  
If for any reason you are not comfortable with removing this, holler.  I don't feel super strongly.
> Reduce extra snapshot builds.

- libs/metrics/community_levels.py
- tests/libs/metrics/community_levels_test.py
Forward-filling the metrics by `MAX_METRIC_LOOKBACK_DAYS - 2` (13 days) knocked the community-level-calculation logic out of sync with the top-level metric forward-filling. 
This caused a situation where the community-level logic determined that the hospital metrics were missing (and set the community level to `None`), but the metrics were still displayed/weren't filtered out by the rest of the API
Full snapshot building with these changes: https://github.com/act-now-coalition/covid-data-model/actions/runs/5084966505
> Fix off-by-one issue causing community levels to go blank
