act-now-coalition/covid-data-model

README.md, requirements.txt
Allows viewing repo in jupyter
=> Address adding mybinder to readme

.github/workflows/my_binder.yml
This PR addressess adding a mybinder action on any PR to master. Useful for testing notebooks or various modules within hosted jupyter
TODO
- [Output Mybinder URL ]
=> Address adding my binder GitHub action on master PR

libs/CovidDatasets.py
I think this fixes the issue you were hitting.
=> Ensure deaths are 0 instead of nan when missing.

README.md
This appears to be regularly updated and from JHU, but cleaned.
=> Adding the Splunk github data

libs/CovidDatasets.py
Later time ranges are formatted as counties. As we were using the last state format date, we were stopping soon.
=> Fix JHU Calculation 03/22-Current

libs/build_dod_dataset.py, requirements.txt
Also add back some requirements that we lost.
=> Start support for COVID_DATA_PUBLIC

requirements.txt, run.py
This splits up preparing the data for the website from the actual writing of the data frame.  
Doing this to make it more flexible to write different kinds of datasets.
=> Split up data writing from preparing data frame for website

libs/CovidTimeseriesModelSIR.py, libs/datasets/beds.py, run.py
- Removes r0 print
- Changes state output to intended output_dir/state/{path}
- use legacy beds for state data
=> 76 fix beds

.gitignore, libs/build_dod_dataset.py
Use the output of creating the state data to generate a 16/32 days out forecast.
=> Use the latest state results to generate 16/32 days out forecast

libs/datasets/dataset_utils.py, run_model.py
Wanted to give this a shot as an example of how the version usage could be simplified a bit.
=> Wrapping option in a decorator to simplify use a bit

libs/datasets/beds.py, libs/datasets/sources/dh_beds.py, test/beds_dataset_test.py
Messed up the rebase in #103, this is the same code as 103, but added nyc aggregation back in.
=> Beds add combined number

libs/datasets/beds.py, libs/datasets/dataset_utils.py, run.py, test/beds_dataset_test.py
This uses the definitive health beds data.
Also, adding stronger checking around index guarantees for any beds dataset.  I'd like to get better at making these assertions earlier, because if we don't have unique indexes, downstream applications can get screwed up.
Open to different ways of doing this as well!
Addresses #113
=> Use DH Beds for state level models

libs/CovidTimeseriesModelSIR.py
not very well tested, i ran this through the notebook 3 times and nothing seemed to break, but that's it.
=> fix for na susceptible and infecteds post-intervetntion... 

.github/PULL_REQUEST_TEMPLATE.md, api/README.md
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/125
=> Add initial PR Template

deploy.sh, deploy_dod_dataset.py, libs/build_dod_dataset.py
Helps address #123, may conflict with @goldblatt PR.
=> Add dod artifacts to deploy sh

deploy_dod_dataset.py, libs/build_dod_dataset.py, libs/constants.py, libs/datasets/can_model_output_schema.py, libs/datasets/model_output_schema.py, libs/datasets/projections_schema.py, libs/datasets/results_schema.py, libs/functions/calculate_projections.py, libs/functions/generate_shapefiles.py, libs/validate_results.py
Hmm something is a lil wrong with the output, but this runs so that's something
=> first pass at reorging the files

libs/functions/calculate_projections.py, libs/functions/generate_shapefiles.py
This just runs the autoformatter on the functions file!
=> running black formatter on functions

api/README.md, run.sh
This PR addresses part of #126.
- [WHAT TESTS?] Are tests passing?
=> Add version.json to API Output.

api/README.md, api/schemas/case_summary.json, api/schemas/county_summaries.json
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/124
It's the first pass.  Our files and schemas are currently all over the place.  
It's probably wiser to fix the problem than document the current situation thouroughly.
=> Document the pre-launch Schema

libs/datasets/sources/covid_tracking_source.py, libs/datasets/timeseries.py
=> Adding cumulative hospitalizations to timeseries

libs/datasets/sources/covid_tracking_source.py
Didn't update the filter, so it wasn't returning all data. Would like to add a test for this eventually
=> Third times a charm... returning rows with total or current data

run.py
=> Add COVID_MODEL_CORES env var override for # of cores to use.

README.md
=> Add Instructions for Job Trigger

libs/datasets/beds.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/181
=> Adding in beds column option

cli/run_dod_dataset.py
Just an easier way to disable validation
=> Making validation enabled by default and setting a flag to disable

libs/datasets/sources/fips_population.py, libs/us_state_abbrev.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/162
=> Adding state level fips to the population table

api/schemas/CANPredictionAPI.json, api/schemas/CANPredictionAPIRow.json
My previous pr checked in code breaking the test and my pydantic version was wrong
=> new day, new pydatnic version

cli/run_top_counties_dataset.py, libs/functions/generate_api.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/206
=> formatting the updated date to be iso format

api/README.md, cli/run_top_counties_dataset.py, libs/pipelines/top_counties_pipeline.py, run.sh
addresses #207
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/207
=> Updating the run.sh to deploy first 100 counties.json

api/README.md, api/can_predictions.py, cli/run_counties_api.py, cli/run_state_api.py, cli/run_states_api.py, libs/enums.py, libs/functions/generate_api.py, libs/pipelines/api_pipeline.py, run.py, run.sh
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/211 & https://github.com/covid-projections/covid-data-model/issues/212
=> Generate API Files for counties/states & Upload to S3

.github/workflows/deploy_api.yml, run.sh
Fix Currently Broken Master Pipeline
https://github.com/covid-projections/covid-data-model/actions/runs/77973051
Use a hosted runner for speed improvements
=> Fix Master Pipeline & Improve Speed

api/can_api_definition.py, cli/run_counties_api.py, cli/run_states_api.py, libs/datasets/can_model_output_schema.py, libs/functions/generate_api.py, libs/functions/get_can_projection.py, libs/pipelines/api_pipeline.py, libs/pipelines/can_model_pipeline.py
This PR addresses issue #210 
- [] Will the *current* schema in [api docs](https://github.com/covid-projections/covid-data-model/blob/master/api/README.md) be updated with this PR?
- [?] Are tests passing?
=> First pass at Adding the timeseries API

libs/functions/generate_api.py, libs/pipelines/api_pipeline.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/232
=> fixing the top county pipeline

cli/run_dod_dataset.py, deploy_dod.sh, libs/functions/calculate_projections.py, libs/functions/get_can_projection.py, libs/pipelines/api_pipeline.py, libs/pipelines/dod_pipeline.py, run.sh
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/235
=> the run.sh file inputs/outputs got a lil confused

libs/functions/calculate_projections.py
=> adding in a better assertion for missing counties

pyseir/deployment/webui_data_adaptor_v1.py, pyseir/ensembles/ensemble_runner.py, pyseir/inference/model_fitter.py, pyseir/load_data.py
Remove hospitalization data filter and add cumulative total infections
=> Remove hospitalization data filter and add cumulative total infections

cli/run_counties_api.py, cli/run_dod_dataset.py, cli/run_states_api.py, libs/build_processed_dataset.py, libs/enums.py, libs/functions/generate_api.py, libs/functions/get_can_projection.py, pyseir/deployment/webui_data_adaptor_v1.py
Reverts covid-projections/covid-data-model#250
=> Revert "return enum instead of the value"

libs/build_processed_dataset.py, libs/datasets/sources/jhu_dataset.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/110
=> Surfacing the latest path and using that to load jhu data

run.sh
=> Move county folder instead of moving individual files

.github/workflows/deploy_api.yml, .gitignore, pyseir/cli.py, run.sh
=> Add Artifacts and Split run.sh jobs

cli/run_counties_api.py, cli/run_dod_dataset.py, cli/run_states_api.py, libs/build_processed_dataset.py, libs/enums.py, libs/functions/generate_api.py, libs/functions/get_can_projection.py, pyseir/deployment/webui_data_adaptor_v1.py
=> Use Enum Value to generate pyseir model files 

.github/workflows/label_api_snapshot.yml
=> Workflow will alert slack when we label something

.github/workflows/deploy_api.yml
=> just run s3 sync

api/can_api_definition.py, api/schemas/CANPredictionTimeseriesRow.json, api/schemas/CovidActNowCountiesSummary.json, api/schemas/CovidActNowCountiesTimeseries.json, api/schemas/CovidActNowStatesSummary.json, api/schemas/CovidActNowStatesTimeseries.json, cli/run_counties_api.py, cli/run_counties_dataset.py, cli/run_states_api.py, cli/run_top_counties_dataset.py, libs/build_processed_dataset.py, libs/dataset_deployer.py, libs/functions/calculate_projections.py, libs/functions/generate_api.py, libs/pipelines/api_pipeline.py, libs/pipelines/top_counties_pipeline.py, run.py, run.sh, test/dataset_deployer_test.py
Adds 4 new files:
```
- us/states(.intervention).{json,csv}
- us/states(.intervention).timeseries.json
- us/states(.intervention).{json,csv}
- us/counties(.intervention).timeseries.json
```
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/268
=> Adding bulk files

pyseir/cli.py, pyseir/deployment/webui_data_adaptor_v1.py, pyseir/inference/fit_results.py, pyseir/inference/model_fitter.py, pyseir/inference/whitelist_generator.py, pyseir/load_data.py, pyseir/models/suppression_policies.py, pyseir/utils.py
Add a display whitelist that restricts which counties get shipped.
=> Add county whitelist

cli/run_counties_api.py, cli/run_states_api.py, libs/pipelines/api_pipeline.py
Addressing changes I meant to get to last night
=> Simplifying state and county summaries a bit

pyseir/deployment/webui_data_adaptor_v1.py
Subset of https://github.com/covid-projections/covid-data-model/pull/287/files just to get the counties fix out
=> Fix inferred counties whitelist

api/can_api_definition.py, cli/run_counties_api.py, cli/run_states_api.py, libs/functions/calculate_projections.py, libs/pipelines/api_pipeline.py
This PR addresses issue https://github.com/covid-projections/covid-data-model/issues/268
=> Adding in csv output summaries for timeseries

api/README.V1.md
added a section talking about the timeseries param.
@asciimike please tell me why it's all broken and wrong
=> Adding Projected Overloads vs Timeseries

api/can_api_definition.py, api/schemas/CovidActNowAreaSummary.json, api/schemas/CovidActNowCountiesAPI.json, api/schemas/CovidActNowCountiesSummary.json, api/schemas/CovidActNowCountiesTimeseries.json, api/schemas/CovidActNowStatesSummary.json, api/schemas/CovidActNowStatesTimeseries.json, libs/functions/generate_api.py, libs/pipelines/api_pipeline.py, test/api/test_can_predictions.py
Instead of using a data: [] style of json just use the []
=> Removing the data from list json schema

api/can_api_definition.py, cli/run_counties_api.py, cli/run_model.py, libs/pipelines/api_pipeline.py, run.py, run.sh
Fixes https://github.com/covid-projections/covid-projections/issues/534
=> Changing county summaries to iterate over model output files to pickup fips

libs/functions/generate_api.py, libs/pipelines/api_pipeline.py, test/api/test_can_predictions.py
Fixes a couple small errors in the api output.
* Ran into a validation error where pandas nan values were sneaking in.
* Also the change to using __root__ broke the timeseries output it looks like - this fixes that and screams louder if it breaks.
=> Fixing a couple small errors in api output

api/can_api_definition.py, api/schemas/CovidActNowAreaSummary.json, api/schemas/CovidActNowCountiesAPI.json, api/schemas/CovidActNowCountiesSummary.json, api/schemas/CovidActNowCountiesTimeseries.json, api/schemas/CovidActNowStatesSummary.json, api/schemas/CovidActNowStatesTimeseries.json, libs/functions/calculate_projections.py, libs/functions/generate_api.py
=> Fixing zero population

pyseir/cli.py
=> Run Black on pyseir/cli.py

pyseir/models/seir_model.py
=> Tweek numpy for performance benefit

pyseir/inference/infer_rt.py, pyseir/inference/whitelist_generator.py
From ~30 seconds to ~5 seconds for whitelist call locally
=> Parallelize pyseir whitelist

api/schemas/CANPredictionTimeseriesRow.json, api/schemas/CovidActNowCountiesTimeseries.json, api/schemas/CovidActNowStatesTimeseries.json, libs/datasets/can_model_output_schema.py, libs/functions/generate_api.py
=> Pick up correct columns for Rt indicators

libs/pipelines/api_pipeline.py
This is the effect on an output file (specifically, `counties/22115.NO_INTERVENTION.timeseries.json`) that formerly included NaN output: https://gist.github.com/davidstrauss/6e3dea58d8d18ad8b2f65b03649ddcd2/revisions
=> Replace encoding implementation to produce compliant JSON

pyseir/inference/infer_rt.py
This PR increases the smoothing scale for Rt to better reduce noise of daily fluctuations to make for more stable product and more accurate reduction of test data systemtatics.
=> Increase Rt smoothing scales and reduce process noise

libs/datasets/__init__.py, libs/datasets/dataset_utils.py, libs/datasets/sources/covid_care_map.py
=> Adding covid care map beds

libs/build_processed_dataset.py, libs/datasets/sources/cds_dataset.py, libs/functions/generate_api.py
=> Add county tests data

.github/workflows/deploy_api.yml, pyseir/inference/model_fitter.py
* Enables a fast and quick model run env var by passing `PYSEIR_FAST_AND_DIRTY=True`
* Disables plotting unless using `PYSEIR_PLOT_RESULTS` as an env var
* dries up some chi-square calculations
* handles retries more precisely
=> Model Fitter Improvements

libs/pipelines/can_model_pipeline.py, pyseir/parameters/parameter_ensemble_generator.py
=> Using ccm instead of dh

api/can_api_definition.py, api/schemas/CANPredictionTimeseriesRow.json, api/schemas/CovidActNowAreaSummary.json, api/schemas/CovidActNowCountiesAPI.json, api/schemas/CovidActNowCountiesSummary.json, api/schemas/CovidActNowCountiesTimeseries.json, api/schemas/CovidActNowStatesSummary.json, api/schemas/CovidActNowStatesTimeseries.json, libs/dataset_deployer.py, libs/datasets/beds.py, libs/datasets/sources/covid_care_map.py, libs/functions/generate_api.py, libs/functions/get_can_projection.py, test/api/test_can_predictions.py, test/beds_dataset_test.py, test/build_processed_data_test.py
This PR addresses issue https://github.com/covid-projections/covid-projections/issues/615
- [] Are the [api docs](https://github.com/covid-projections/covid-data-model/blob/master/api/README.V1.md) updated?
These are intentionally not updated
=> Adding utilization data

api/can_api_definition.py, api/schemas/CANPredictionTimeseriesRow.json, api/schemas/CovidActNowAreaSummary.json, api/schemas/CovidActNowCountiesAPI.json, api/schemas/CovidActNowCountiesSummary.json, api/schemas/CovidActNowCountiesTimeseries.json, api/schemas/CovidActNowStatesSummary.json, api/schemas/CovidActNowStatesTimeseries.json, libs/dataset_deployer.py, libs/datasets/beds.py, libs/datasets/sources/covid_care_map.py, libs/functions/generate_api.py, libs/functions/get_can_projection.py, pyseir/parameters/parameter_ensemble_generator.py, test/api/test_can_predictions.py, test/beds_dataset_test.py, test/build_processed_data_test.py
=> Adding real utilization to model

libs/datasets/data_source.py, pyseir/inference/model_fitter.py, pyseir/load_data.py
by calling .timeseries() on the data, we were filling in Null values, this adds an option to the timeseries to not return null values.  It may be we want to standardize this a bit more, but the easiest solution for right now
=> Fill na values

libs/datasets/sources/covid_care_map.py
=> Override Washoe County ICU Actuals

libs/datasets/beds.py, libs/datasets/custom_aggregations.py, test/beds_dataset_test.py
This is a bit hacky - would eventually like to put some logic to pass in which columns can do weighted averages, but too much complexity for right now.
Just computes the weighted average for the occupancy rates in bed data
=> Adding weighted average of bed utilization rates for nyc borough

libs/datasets/sources/covid_care_map.py
=> Only use NHA for capacity, not utilization

libs/build_processed_dataset.py, libs/pipelines/api_pipeline.py, test/api/test_can_predictions.py
The comment isn't perfect, but hopefully it's a bit more parseable.
=> Fixing up root data changes from Pr comments

api/can_api_definition.py, libs/build_processed_dataset.py
=> Fix testing timeseries data pulling in county data as well

libs/build_processed_dataset.py
=> Deduplicate testing data on fips + date and add sentry message

api/can_api_definition.py, libs/datasets/dataset_utils.py, libs/datasets/latest_values_dataset.py, libs/datasets/timeseries.py, libs/functions/generate_api.py, test/api/test_can_predictions.py, tools/label-api.sh
Adding the api for the actual timeseries
=> Adding api for timeseries of actuals

pyseir/inference/model_fitter.py
This PR addresses the broken data build as mentioned at https://covidactnow.slack.com/archives/C0110QQAPJA/p1588790597050700?thread_ts=1588784403.034400&cid=C0110QQAPJA
=> change some self attributes to locals, fixing crash in data build

pyseir/cli.py
=> call cache at beginning of pyseir

libs/datasets/sources/covid_tracking_source.py
Removes the 'current icu' data in the covid tracking dataset anytime it is greater than the 'current hospitalized' amount. Motivated by covid-tracking providing a new value for Delaware current ICU that is not consistent with the capacity and hospitalized data.
Also added an assert statement to check for this condition going forward once the Delaware problem is fixed upstream.
This PR compensates for https://github.com/COVID19Tracking/issues/issues/416.
- [N/A] Are the [JSON schemas](https://github.com/covid-projections/covid-data-model/tree/master/api/schemas) updated?
- [N/A] Are the [api docs](https://github.com/covid-projections/covid-data-model/blob/master/api/README.V1.md) updated?
- [Yes] Are tests passing?
=> Update covid_tracking_source to check and scrub non-sense ICU values

run.sh
https://trello.com/c/i8M7rKKB/127-preserve-pyseir-stdout-during-automated-snapshot-builds
=> tee stdout instead of only redirecting to a file

libs/datasets/sources/nytimes_dataset.py, pyseir/load_data.py
=> Removes more ad hoc calls to nytimes github repo.

libs/datasets/sources/cds_dataset.py, test/cds_dataset_test.py
This code is outputting a warning which will be easier to fix with a test in place. This is part of https://trello.com/c/HLf7QmJD/118-fix-pyseir-settingwithcopywarning
=> add test for CDSDataset city/county dedup and patching

pyproject.toml
Follow up from https://github.com/covid-projections/covid-data-public/pull/46#discussion_r423890837
=> pyproject black line-length = 100

.github/workflows/python_unit_tests.yml, cli/run_counties_api.py, cli/run_data.py, cli/run_states_api.py, cli/run_top_counties_dataset.py, setup.py, test/cds_dataset_test.py, validate.py
Runs black as a linting github action step
=> adding black linter

libs/datasets/dataset_filter.py, libs/datasets/latest_values_dataset.py, libs/datasets/timeseries.py, test/timeseries_test.py
* replace `DatasetFilter.__init__` with pydantic dataclass and explicitly list the filters used
* add timeseries_test.py
* rm get_subset county= param that seems unused
Done while working towards https://trello.com/c/HLf7QmJD/118-fix-pyseir-settingwithcopywarning
=> Some timeseries get_subset cleanup

pyseir/inference/infer_rt.py
=> Sets np seed at the instance level as well, for r_t infernece.

test/build_processed_data_test.py, test/combined_dataset_test.py
This PR adds some tests so I can more easily fix
https://trello.com/c/tQj1yUjh/145-cds-data-source-missing-proper-county-level-data
without breaking existing code.
=> Add more build_processed_data tests

libs/build_processed_dataset.py
This doesn't have a test for it - would like to get one for the api code soon.  Can address that now, or just get this fix in and make a task for it
=> Fix county level level date type

.github/workflows/deploy_api.yml, run.sh
=> adding SLACK_WEBHOOK to the env for the github action

libs/datasets/timeseries.py, test/timeseries_test.py
fix missing state param in TimeseriesDataset.get_subset and add more tests
=> fix missing state param in TimeseriesDataset.get_subset

README.md, cli/utils.py, libs/github_utils.py, run.py
Added in a helper function to make it easy to download the latest model output snapshot - just makes it easier to debug api generation locally
=> Adding a command line function to download the latest model output artifact from github

libs/datasets/dataset_cache.py, pyseir/cli.py, run.py, run.sh, test/conftest.py
Merge the dataset improvements into master instead
=> Default Dataset caching to enabled and improve logging (#444)

cli/compare_snapshots.py
=> update the url of the slack message to use the correct snapshot in the link

pyseir/inference/model_fitter.py
This adds the chi2_total score to MLE report plots and increases title size
=> Minor Aesthetic Changes to MLE plots

.github/workflows/deploy_api.yml, tools/maybe-trigger-web-snapshot-update.sh
Fixes https://trello.com/c/6shjpYaM
=> Automatically trigger covid-projections update-snapshot job after snapshot build completes.

.github/workflows/python_unit_tests.yml
=> Pin unit-tests workflow to working covid-data-public

.github/workflows/deploy_api.yml, pyseir/ensembles/ensemble_runner.py, pyseir/inference/model_fitter.py, pyseir/models/suppression_policies.py
This PR creates a third stage for the SEIR model
- [ irrelevant] Are the [JSON schemas](https://github.com/covid-projections/covid-data-model/tree/master/api/schemas) updated?
- [ irrelevant] Are the [api docs](https://github.com/covid-projections/covid-data-model/blob/master/api/README.V1.md) updated?
- [ so far! ] Are tests passing?
=> SEIR Third Stage 

.github/workflows/deploy_api.yml, cli/compare_snapshots.py
=> send qa messages to dev-alerts

notebooks/icu_debugging/ICU_INVESTIGATION_TEMPLATE.ipynb, pyseir/ensembles/ensemble_runner.py, pyseir/inference/model_fitter.py
This is a regression bug that was fixed on one of the 3rd stage test branches, but not on the one that actually got merged into master :(
=> Update Scenario Planner Code for Third Stage

api/can_api_definition.py, test/combined_dataset_test.py
This PR addresses https://trello.com/c/6nAAFMJd/210-debug-cmdc-county-data-getting-to-output
Also fixes formatting of `api/can_api_definition.py`
=> add test for CA county level testing and ICU usage

libs/datasets/combined_datasets.py, libs/datasets/sources/cmdc.py, test/combined_dataset_test.py
This change follows https://github.com/covid-projections/covid-data-model/pull/480 and https://github.com/covid-projections/covid-data-public/pull/57
=> change cmdc back to mapping CURRENT_ICU and do same in test.

libs/datasets/combined_datasets.py, libs/datasets/sources/cmdc.py
Fields were added in data source with https://github.com/covid-projections/covid-data-public/pull/63 and won't pass until it is merged.
=> add new CMDC fields

libs/functions/generate_api.py, pyseir/deployment/webui_data_adaptor_v1.py
=> Switch to outputting eps2 instead of eps

tools/maybe-trigger-web-snapshot-update.sh
This reverts commit 6ed0b34b913a68eb24803bcf7cd9018ad3da6f8f. We want to go back to the morning build.
=> Go back to morning snapshot build for website PR generation.

libs/datasets/sources/nha_hospitalization.py
This PR follows up from https://github.com/covid-projections/covid-data-public/pull/71
=> read NHA data from states/nv and change field names

libs/build_processed_dataset.py, libs/datasets/common_fields.py, libs/datasets/data_source.py, libs/datasets/dataset_base.py, libs/datasets/latest_values_dataset.py, libs/datasets/projections_schema.py, libs/datasets/results_schema.py, libs/datasets/sources/cds_dataset.py, libs/datasets/sources/covid_care_map.py, libs/datasets/sources/covid_tracking_source.py, libs/datasets/sources/dh_beds.py, libs/datasets/sources/fips_population.py, libs/datasets/sources/jhu_dataset.py, libs/datasets/sources/nha_hospitalization.py, libs/datasets/sources/nytimes_dataset.py, libs/datasets/sources/test_and_trace.py, libs/datasets/timeseries.py, libs/functions/calculate_projections.py, libs/functions/generate_api.py, libs/validate_results.py, pyseir/load_data.py, pyseir/parameters/parameter_ensemble_generator.py, test/build_processed_data_test.py, test/combined_dataset_test.py
=> rm model repo CommonFields, using instead datapublic version.

pyseir/inference/infer_rt.py
Load raw county level data by fips. Previously used state-level result : /
=> fix county level saved results

.github/workflows/deploy_api.yml, libs/pipelines/api_pipeline.py, test/libs/api_pipeline_test.py
This re-enables all county output. Marking this as DNM until the website is updated to handle counties where projections are not included
=> Reenable all counties

data/latest.csv, data/latest.json, data/timeseries.csv, data/timeseries.json, tools/push-data-update.sh
Getting closer to having this automated, but:
* Updates data from latest build
* fixes the update and commit script.
I still need to properly setup the github actions to kick this off automatically so I'm not running it locally.
=> Update data for 07/15 and fix script to be executable for data update

.github/workflows/update_repo_datasets.yml
Fixes the update action which was breaking because of an incorrect python version
=> Fix update action

pyseir/inference/model_fitter.py
Change the logging of the model fitter in order to easily scrape the model outputs from the logs. This will be used to compare changes in chi2 across different snapshots.
The data was already being logged, but in a pretty print format that made scraping more difficult than necessary. If this is useful, we should either persist this to disk separately or have a machine readable logfile (JSON rendered via Structlog Processor).
For now the log looks like:
> 2020-07-13T23:01:48.2483531Z 2020-07-13T23:01:48.247233Z [info     ] Fit results for Kentucky:      results=###{"fips": "21", "R0": 4.482115538699791, "t0": 65.02883228328865, "eps": 0.23906866301105412, "t_break": 12.060377514977494, "eps2": 0.2481693364547316, "t_delta_phases": 68.23408248192712, "test_fraction": 0.03069106145658089, …
=> Changed ModelFitter Logging to Dump Fit Results in JSON Readable Format

pyseir/cli.py
This just refactors the pyseir cli a bit.  It pushes more responsibility to calling functions to know the list of states we will call with.  The intent here is to reduce the recursion in the helper functions and make those easier for me (and hopefully others) to understand.
=> Streamlining pyseir cli to always take in lists of states

libs/datasets/sources/can_pyseir_location_output.py, test/libs/datasets/sources/can_pyseir_location_output_test.py
Addresses https://sentry.io/organizations/covidactnow/issues/1790325990/?project=5203044&query=is%3Aunresolved
=> Fix KeyError when no rt exists

requirements_test.txt
Unit tests were failing locally for brett (and myself) with some weird garbage - thinking it might've been because of a mac os change, but not 100% sure.  Upgrading xdist did the trick for me
=> Upgrade xdist

libs/datasets/combined_datasets.py, libs/datasets/sources/covid_county_data.py, libs/notebook_helpers.py, test/combined_dataset_test.py
Uses the new covid-county-data files saved in covid-data-public
=> Rename cmdc -> covid county data

.github/workflows/update_repo_datasets.yml, libs/qa/data_availability.py
Makes a couple ranges dynamic and adds the sheet url to a slack alert
=> Fix dynamic sheet ranges

libs/pipelines/api_pipeline.py, libs/series_utils.py, libs/top_level_metrics.py, test/libs/top_level_metrics_test.py
A couple more small tweaks to fix how data is calculated when data backslides
=> Tweaking averages to more accurately match the website

api/README.V1.md, api/can_api_definition.py, api/schemas/AggregateRegionSummary.json, api/schemas/AggregateRegionSummaryWithTimeseries.json, api/schemas/Metrics.json, api/schemas/MetricsTimeseriesRow.json, api/schemas/RegionSummary.json, api/schemas/RegionSummaryWithTimeseries.json, libs/top_level_metrics.py, test/libs/top_level_metrics_test.py
This adds in the contact tracing metric to the API output. 
Don't think there's anything too fancy here - next up will be rt
=> Adding contact tracing to API output

libs/pipeline.py
Addresses: https://sentry.io/organizations/covidactnow/issues/1858440487/?project=5203044&referrer=slack
=> Adding pyseir rt patch import

pyseir/cli.py, pyseir/ensembles/ensemble_runner.py
* merge ensemble_runner._run_county and run_state into run_region
* move states_only=False logic to the one place using it.
=> merge ensemble_runner run functions

api/README.V1.md, api/can_api_definition.py, api/schemas/AggregateRegionSummary.json, api/schemas/AggregateRegionSummaryWithTimeseries.json, api/schemas/Metrics.json, api/schemas/MetricsTimeseriesRow.json, api/schemas/RegionSummary.json, api/schemas/RegionSummaryWithTimeseries.json, libs/pipelines/api_pipeline.py, libs/top_level_metrics.py, test/libs/generate_api_test.py, test/libs/top_level_metrics_test.py
This adds in the infection rate and infection rate confidence interval into the metrics output.
A bit of annoying logic to pull the rt from 7 days in the past, but came out alright.
=> Add infection rate

pyseir/cli.py, pyseir/deployment/webui_data_adaptor_v1.py, pyseir/inference/model_fitter.py
put state fitters in a map and pass them to county model_fitter.RegionalInput.from_region
=> pass state fitters to county fitter input

libs/datasets/dataset_utils.py, pyseir/inference/model_fitter.py, pyseir/inference/whitelist.py, pyseir/load_data.py, pyseir/utils.py
* rm some unused methods in `dataset_utils.py`
* rm code for reading and writing whitelist
=> rm unused methods

libs/pipelines/api_pipeline.py, libs/us_state_abbrev.py, test/infer_rt_test.py, test/libs/api_pipeline_test.py
This will add in a few more regions where we might not have data but clicking on them will trigger an error.  Specifically this will add all of the mariana island "counties"
=> Dont skip output if timeseries is empty

libs/pipeline.py, pyseir/cli.py, pyseir/deployment/webui_data_adaptor_v1.py, pyseir/ensembles/ensemble_runner.py, pyseir/inference/model_fitter.py, pyseir/rt/infer_rt.py
Small refactor for combined data regional input to load the timeseries + latest data right away.
=> Refactor combined datasets regional input

pyseir/deployment/webui_data_adaptor_v1.py, test/pyseir/icu/infer_icu_test.py
replace more webui_data_adaptor_v1.RegionalInput method access with attribute access. See  https://google.github.io/styleguide/pyguide.html#213-properties and https://stackoverflow.com/a/1555169  for rationale.
It looks like I didn't merge https://github.com/covid-projections/covid-data-model/pull/671/files into https://github.com/covid-projections/covid-data-model/pull/656 but not sure why it tested green in github.
=> replace more webui RegionalInput method access with attribute access

notebooks/rt_inference/rt_autosigma.ipynb
=> Add autosigma notebook

.github/workflows/deploy_docs.yml, tools/deploy-docs.sh
Adding this as a dispatch since we currently only have a master branch.
=> Adding docs deploy action + tool

pyseir/cli.py
Mass counties now seem to work! Adding back in
=> Adding massachussetts counties back in

api/README.V1.md, api/README.V1.tmpl.md, api/docs/docs/access.mdx, api/docs/docs/migration.md, api/docs/open_api_schema.json, api/update_open_api_spec.py
Adding a couple more top-level examples + api warning + more migration tips
=> Adding examples + better documentation

pyseir/cli.py, test/pyseir_end_to_end_test.py
fixes https://sentry.io/organizations/covidactnow/issues/1912090842/
=> Fixing bug in infer_rt_regions + adding test

api/README.V1.md, api/README.md, api/__init__.py, api/schemas_v2/Actuals.json, api/schemas_v2/ActualsTimeseriesRow.json, api/schemas_v2/AggregateFlattenedTimeseries.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/HospitalResourceUtilization.json, api/schemas_v2/Metrics.json, api/schemas_v2/MetricsTimeseriesRow.json, api/schemas_v2/MetricsTimeseriesRowWithHeader.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, cli/api.py
Adds in V2 Schemas, used to generate types on the website
=> Add api v2 schemas

.github/workflows/deploy_api.yml
This removes the api result folder after the build is finished
=> Clean up data dir build

api/can_api_v2_definition.py, api/docs/open_api_schema.json, api/schemas_v2/RegionTimeseriesRowWithHeader.json, api/update_open_api_spec.py, libs/dataset_deployer.py, libs/functions/build_api_v2.py, libs/pipelines/api_v2_paths.py, libs/pipelines/api_v2_pipeline.py, test/dataset_deployer_test.py, test/libs/api_v2_pipeline_test.py
Generates bulk timeseries csvs + updates api documentation to match.
=> Adding bulk timeseries csvs

libs/datasets/timeseries.py
split MultiRegionTimeseriesDataset.from_dataframes into from_timeseries_df and append_latest_df
=> Better support for making MultiRegion without latest values

libs/google_sheet_helpers.py
Note: I couldn't figure out the actual sheet that got written to, so I'm not 100% sure if this did reasonable things or not...  but it didn't crash.  🤷‍♂️
=> Move data availability report to MULTI_REGION dataset.

libs/datasets/combined_datasets.py
This is part of https://trello.com/c/6ZPv7k9T/477-revamp-test-positivity-calculation
=> add data columns needed by test positivity

.github/workflows/update_api_usage.yml, cli/utils.py, libs/google_sheet_helpers.py, libs/update_api_user_metrics.py, test/libs/api_usage_updater_test.py
This adds in a cli command to update a google sheet with the latest API User activity.  
execution:
```
./run.py utils update-api-user-usage
```
=> Adding api users updater

api/awsauth/awsauth/api_key_repo.py, api/awsauth/awsauth/auth_app.py, api/awsauth/awsauth/config.py, api/awsauth/awsauth/dynamo_client.py, api/awsauth/awsauth/email_repo.py, api/awsauth/awsauth/firehose_client.py, api/awsauth/awsauth/ses_client.py, api/awsauth/awsauth/the_registry.py, api/awsauth/awsauth/welcome_email.html, api/awsauth/serverless.yml
This addresses a couple of issues that we were seeing in the API.
Also I added a registry that contains initialized connections.  This should drop the latency by only making a connection once per container rather than on every request.
=> Small api fixes

libs/pipelines/api_pipeline.py
Changing log from error -> warning to quiet sentry
=> Quiet sentry log

api/docs/docs/about.md, api/docs/docs/contact.md
We wrote this copy before we had the api@covidactnow email.  This updates those references
=> Change email from info to api

api/awsauth/awsauth/auth_app.py, api/awsauth/awsauth/config.py, api/awsauth/awsauth/hubspot_client.py, api/awsauth/awsauth/the_registry.py, api/awsauth/requirements.txt
This automatically adds contacts to hubspot when they register.  
Makes it easier for us to keep track of signups and reach out as needed
=> Adding hubspot create on reg

tools/trigger-update-datasets.sh
Just a script that lets us run the dataset update independently
=> Add dataset update trigger

pyseir/rt/infer_rt.py, pyseir/rt/plotting.py, test/infer_rt_test.py, test/mocks/inference/load_data.py
Removes the code for handling deaths in the Rt calculation.
=> Remove deaths from rt

api/awsauth/awsauth/welcome_email.html, api/docs/docs/access.mdx, api/docs/open_api_schema.json, api/update_open_api_spec.py
* Adds a couple more examples for timeseries csvs
* Updates commercial usage text in email
=> Add csv examples

api/awsauth/awsauth/auth_app.py, api/awsauth/serverless.yml
Removes old API Gateway register/check code
=> Removing API gateway lambda functions

pyseir/cli.py
Follow up to https://covidactnow.slack.com/archives/C011Z21ST8V/p1603980520002100
=> Log location when infer_rt fails. mk output directory

api/docs/open_api_schema.json, api/schemas_v2/AggregateFlattenedTimeseries.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Metrics.json, api/schemas_v2/MetricsTimeseriesRow.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RegionTimeseriesRowWithHeader.json
Output of running `./run.py api update-v2-schemas`
=> Update API schemas.

.github/workflows/deploy_api.yml, tools/maybe-trigger-label-api.sh
Adds a trigger to run label-api automatically on the morning build
=> Trigger label api on morning build

libs/datasets/combined_datasets.py, libs/datasets/timeseries.py, pyseir/icu/infer_icu.py, test/libs/api_pipeline_test.py, test/libs/datasets/timeseries_test.py
=> add OneRegionTimeseriesDataset.region

api/docs/docs/access.mdx, api/docs/src/components/SignupForm.jsx, api/docs/src/components/SignupForm.style.jsx
Update text to be more clear how to use the API key
https://trello.com/c/RBdY0LM2/539-copy-change-update-csv-download-description-to-explain-what-the-query-string-change-requires
=> Change {apiKey} -> YOUR_KEY_HERE

pyseir/cli.py
Instead of re-raising the exception, just logging and exception and continuing on.  Will get to the root cause later today, but want to get the build otu
=> dont raise error on failed region

.github/workflows/deploy_api.yml, tools/build-snapshot.sh
Updates deploy_api to use workflow dispatch.
=> Add workflow dispatch for deploy_api

.github/workflows/deploy_api.yml
Fixes github ref parsing to set environment variable
=> Fix GitHub ref

libs/datasets/timeseries.py, test/beds_dataset_test.py, test/libs/datasets/timeseries_test.py
=> Better empty timeseries handling

tools/build-snapshot.sh
Was referring to the wrong filename for the deploy api workflow :/
=> Fix name of deploy_api file called in build-snapshot.sh

cli/api.py
This PR expands `api generate-test-positivity` to add writing the output of the API and allow filtering to just one fips or state.
This is makes checking if a branch produces identical test positivity values as master much easier, which will be useful for future refactoring work.
Tested by running  `./run.py api generate-test-positivity --state=RI` and looking at `results/output/test-positivity-output.csv`.
=> test positivity debug output

.github/workflows/update_repo_datasets.yml
Disabling country aggregation for now as there are a handful of parts of the downstream pipeline that break.  
made https://trello.com/c/EyISOtVY/623-country-aggregation-breaking-pyseir-output-and-doesnt-output-api-files-properly  for fixing that
=> Disable country aggregation

libs/datasets/sources/test_and_trace.py
=> clean lint error in test_and_trace.py

api/docs/open_api_schema.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/ICUHeadroomMetricDetails.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RiskLevels.json, api/schemas_v2/TestPositivityRatioDetails.json
Updates a few api schemas that i had missed
=> update api schemas to include url + new risk level

api/can_api_v2_definition.py, api/docs/open_api_schema.json, api/schemas_v2/AggregateFlattenedTimeseries.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Metrics.json, api/schemas_v2/MetricsTimeseriesRow.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RegionTimeseriesRowWithHeader.json, api/schemas_v2/TestPositivityRatioDetails.json, libs/datasets/combined_datasets.py, libs/datasets/sources/cdc_testing_dataset.py, libs/test_positivity.py
This adds in the CDC Dataset to combined datasets but doesn't yet enable it in test positivity
=> Add cdc data source

libs/datasets/timeseries.py
A little change, part of https://trello.com/c/EyISOtVY/623-country-aggregation-breaking-pyseir-output-and-doesnt-output-api-files-properly
=> rm Missing fips log. reduce 'Re-adding empty columns' to debug level.

cli/api.py, libs/metrics/test_positivity.py
This makes it easier to test that data hasn't changed while working on https://trello.com/c/6ZPv7k9T/477-clean-up-redundant-test-positivity-calculation-code-api-vs-combined-dataset
=> hacky change to how test positivity CSVs are written

.github/workflows/deploy_api.yml, api/can_api_v2_definition.py, api/docs/docs/updates.md, api/docs/open_api_schema.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RiskLevelTimeseriesRow.json, api/schemas_v2/RiskLevels.json, libs/build_api_v2.py, libs/metrics/top_level_metric_risk_levels.py, libs/pipelines/api_v2_pipeline.py, test/libs/generate_api_v2_test.py, test/libs/metrics/top_level_metric_risk_levels_test.py, test/libs/metrics/top_level_metrics_test.py
Still need to fix/update tests and docs, but this is my attempt at the risk level timeseries.  I went with the ugly approach - the whole risk level code needs a refactor, but don't think i can do that and get in this feature.
=> First working version of risk level based on 3 metrics + risk level timeseries

api/can_api_v2_definition.py, libs/build_api_v2.py
Tested this by running locally and verifying output in csv file - will add a trello ticket to add a real test to this part of the output
=> Adding risk level to csv output

api/docs/package.json, api/docs/yarn.lock
I'm trying to debug an issue where there is a weird flicker from the home page to the requested url on page load, I think this is causing google to think that the home page is every link.  Testing this locally I definitely get a more promising result - so think this version bump may actually work
=> Upgrade docusaurus to try and fix indexing issue

test/infer_rt_test.py
See https://covidactnow.slack.com/archives/C0110QQAPJA/p1609803013425300
=> Bath County got too sick, replaced with Highland County

libs/datasets/timeseries.py, test/libs/datasets/timeseries_test.py
This PR is part of https://trello.com/c/Cq2zNk2M/674-annotate-data-outliers-that-weve-flagged-in-the-ui
=> Use `tag` attribute to store provenance in a dataset

cli/data.py, libs/datasets/custom_aggregations.py, libs/datasets/timeseries.py, test/libs/datasets/custom_aggregations_test.py, test/libs/datasets/timeseries_test.py
Uses similar aggregation to NYC boroughs to replace DC county data with state data
=> Replace DC County Data with DC State data

data/CDCTesting-wide-dates.csv, data/CMSTesting-wide-dates.csv, data/HHSHospital-wide-dates.csv, data/HHSTesting-wide-dates.csv, data/NYTimes-wide-dates.csv, data/TestAndTrace-wide-dates.csv, data/USAFacts-wide-dates.csv, data/Valorum-wide-dates.csv, data/covid_tracking-wide-dates.csv, data/multiregion-provenance.csv, data/multiregion.csv, data/tx_hosp-wide-dates.csv, libs/datasets/timeseries.py, test/libs/datasets/timeseries_test.py
This PR addresses https://trello.com/c/6W0oakD2/711-github-usage-investigate-low-hanging-fruits
=> Retire 165MB wide variables CSV

libs/build_api_v2.py, libs/dataset_deployer.py, libs/pipelines/api_v2_pipeline.py, test/dataset_deployer_test.py, test/libs/metrics/test_positivity_test.py
Adds support for removing entire sub keys and removes annotations from csvs for now
=> Remove annotations keys when writing to csv

api/docs/open_api_schema.json, api/update_open_api_spec.py
Updates reference to point to excel sheet of cbsa codes
=> Update CBSA code reference

libs/datasets/combined_datasets.py, libs/datasets/sources/can_scraper_state_providers.py
Adds in state provider data from can scrapers
=> Add state providers

data/multiregion-static.csv, data/multiregion-wide-dates.csv, data/multiregion.json, libs/datasets/statistical_areas.py, test/libs/datasets/statistical_areas_test.py
Turns out I wasn't passing the required reporting ratio through 🤦 so it was just aggregating all data regardless if it has missing data or not.  I'm running a snapshot to double check that these changes will turn out to reflect reality
=> Fix aggregation required rate

api/docs/docs/about.md, api/docs/src/components/SignupForm.jsx
Worked on updated meta description with gaia + add in GA event on API signup
=> Add GA event to signup form + update meta description

api/docs/package.json, api/docs/src/pages/api.js, api/docs/yarn.lock
Removed the yarn.lock file and reran updating some of the components. Mostly fixes a problem where anchor links weren't showing up on headers.
=> Update docs packages + fix scroll in api reference

dash_app.py, libs/datasets/taglib.py, libs/datasets/tail_filter.py, libs/datasets/timeseries.py, tests/libs/datasets/taglib_test.py, tests/libs/datasets/tail_filter_test.py, tests/libs/datasets/timeseries_test.py, tests/test_helpers.py
=> Extract tag code from timeseries to taglib

api/docs/docs/about.md
Adds a small note to the intro text mentioning vaccinations
=> Add note to headline

dash_app/dashboard.py
=> add git commit to dash page

services/data-pipeline-dashboard/README.md, services/data-pipeline-dashboard/uwsgi.ini
* Add info about cloud monitoring in README
* reduce uwsgi to 3 processes to reduce memory usage.
=> Reduce dashboard memory woes

.github/workflows/deploy_aws_api_infrastructure_dev.yml
This needs to be in master for me to test locally
=> Add basic template so I can play around with locally

libs/datasets/timeseries.py, tests/libs/datasets/timeseries_test.py
=> add test and fix for region without annotations

api/docs/open_api_schema.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Annotations.json, api/schemas_v2/AnomalyAnnotation.json, api/schemas_v2/FieldAnnotations.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json
Just running schema update to get the new source object in
```
./run.py api update-schemas
```
=> Update schemas with source object

.github/workflows/deploy_aws_api_infrastructure_dev.yml
Has an improper github action workflow spec, so was never deploying to prod
=> Fix inputs to actually deploy to prod

dash_app/dashboard.py
Add count of timeseries, url and the difference (ie timeseries without url) to the Regions table. This helps to expose places where we can add more URLs.
Example output:
There are some counties with more URLs than timeseries, for example the following have a URL but no real value:
```
iso1:us#iso2:us-nv#fips:32009,vaccinations_completed
iso1:us#iso2:us-nv#fips:32009,vaccinations_initiated
iso1:us#iso2:us-nv#fips:32009,vaccines_administered
```
=> add more counts to Regions table

api/docs/docusaurus.config.js, api/docs/static/scripts/gtag_conversion_event.js
Should help with Google ads conversion tracking
=> Adding gtag tracking id to docs

libs/datasets/combined_datasets.py, tests/libs/datasets/combined_dataset_utils_test.py
Removes IA counties from NYTimes dataset so we fall back on USA facts
=> Also exclude IA counties from NYTimes dataset

tests/libs/generate_api_v2_test.py
=> fix test_build_summary_for_fips by adding anomalies

api/can_api_v2_definition.py, api/docs/docs/updates.md, api/docs/open_api_schema.json, api/schemas_v2/Actuals.json, api/schemas_v2/ActualsTimeseriesRow.json, api/schemas_v2/AggregateFlattenedTimeseries.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Annotations.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RegionTimeseriesRowWithHeader.json, libs/build_api_v2.py, libs/pipelines/csv_column_ordering.py, tests/libs/api_v2_pipeline_test.py, tests/libs/generate_api_v2_test.py
Adds new deaths to the API output
=> Add new deaths to api

tests/libs/datasets/sources/can_scraper_helpers_test.py
After I added the aggregate level addition, needed to fix the expected output of this test
=> fix CAN Scraper tests

Makefile
=> add `make test-fast`

cli/data.py, libs/datasets/custom_aggregations.py, tests/libs/datasets/custom_aggregations_test.py
Adds fixes for PR static value aggregation + adds a helper flag that skips all dataset filters
=> Chris fixes for PR

libs/datasets/timeseries.py, tests/libs/datasets/timeseries_test.py
=> rm unused provenance_map

libs/datasets/outlier_detection.py
This PR addresseses https://trello.com/c/7J2SmDnr
Running
```
mv data/multiregion-wide-dates.csv data/multiregion-wide-dates-demo.csv
csvcut -C demographic_bucket data/multiregion-wide-dates-demo.csv | perl -np -e 's/,+$//' > data/multiregion-wide-dates.csv
git difftool --no-prompt -t vimdiff main -- data/multiregion-wide-dates.csv
```
found that the implementation before this PR filtered `iso1:us#iso2:us-ms#fips:28057,test_positivity_7d` leaving `"{""date"": ""2021-03-10"", ""original_observation"": 0.0196}"` while with this PR the original observation was left. Copying the values to a unittest didn't filter with the old or new code because the zscore was only 1.477, way less than the threshold of 10. Mysterious.
=> change outlier_detection.py to use wide dates

services/webhook/update.sh
=> on dashboard lfs prune after update to reduce disk usage growth

libs/datasets/outlier_detection.py, tests/libs/datasets/outlier_detection_test.py
=> fix drop_series_outliers bucket handling

libs/datasets/timeseries.py, tests/libs/datasets/timeseries_test.py
=> bucket support in get_regions_subset and remove_regions

api/can_api_v2_definition.py, api/docs/open_api_schema.json, api/schemas_v2/Actuals.json, api/schemas_v2/ActualsTimeseriesRow.json, api/schemas_v2/AggregateFlattenedTimeseries.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Annotations.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RegionTimeseriesRowWithHeader.json, libs/build_api_v2.py, libs/pipelines/csv_column_ordering.py, tests/libs/generate_api_v2_test.py
Adds administered vaccines to API
=> Add vaccines administered

tests/libs/datasets/custom_aggregations_test.py
=> actually test aggregate_puerto_rico_from_counties

cli/data.py
I would like to remove the backing code - will follow up with that.  we may be using it for CO, but wanted to get this out to unbreak the build
=> Remove CA Vaccination backfill

dash_app/dashboard.py, libs/datasets/timeseries.py, tests/libs/datasets/timeseries_test.py
=> MultiRegionDataset.static_and_geo_data for dashboard

dash_app/dashboard.py, libs/qa/timeseries_stats.py, tests/libs/qa/timeseries_states_test.py
=> move aggregation stuff out of dashboard.py and add test

api/can_api_v2_definition.py, libs/build_api_v2.py, libs/datasets/demographics.py, libs/datasets/sources/can_scraper_helpers.py, libs/datasets/timeseries.py, pyseir/icu/infer_icu.py, tests/api/can_api_v2_definition_test.py, tests/libs/build_api_v2_test.py, tests/libs/datasets/demographics_test.py, tests/libs/datasets/timeseries_test.py, tests/libs/generate_api_v2_test.py
This is just a first pass at trying to pass the demographic data through to the API.
There's a bit of duplication with latest and bucketed_latest in one region, but I think we kinda need it for now until static has buckets.
=> [WIP] Prototype of demographic data in API

pyseir/utils.py
Some cleanup for https://trello.com/c/EyISOtVY/623-usa-data-aggregation-in-pipeline-doesnt-work
=> rm unused RunArtifact constants

pyseir/utils.py, tests/pyseir/utils_test.py
Some cleanup for https://trello.com/c/EyISOtVY/623-usa-data-aggregation-in-pipeline-doesnt-work
=> Add get_run_artifact_path test. rm a little unused code.

pyseir/utils.py, tests/pyseir/utils_test.py
for https://trello.com/c/EyISOtVY/623-usa-data-aggregation-in-pipeline-doesnt-work
=> restructure get_run_artifact_path and support COUNTRY

.github/workflows/update_repo_datasets.yml, libs/pipelines/api_v2_pipeline.py
=> rm --no-aggregate-to-country from .github/workflows/update_repo_datasets.yml

api/docs/.eslintrc.js, api/docs/.prettierrc.js, api/docs/package.json, api/docs/src/components/Redocusaurus.jsx, api/docs/src/components/SignupForm.jsx, api/docs/src/components/SignupForm.style.jsx, api/docs/src/pages/access.js, api/docs/src/pages/api.js, api/docs/tsconfig.json, api/docs/yarn.lock
Adds typescript support + setting up eslint/prettier configs. 
Not manually changing any code here, just settting up the base - will change existing files in another PR
=> Typescriptify api docs

api/awsauth/awsauth/auth_app.py, api/awsauth/awsauth/hubspot_client.py, api/docs/docusaurus.config.js, api/docs/package.json, api/docs/src/components/SignupForm.style.tsx, api/docs/src/components/SignupForm.tsx, api/docs/src/components/TextFieldWrapper.tsx, api/docs/yarn.lock
=> Adding signup form

libs/datasets/timeseries.py
=> read/write to paths instead of DatasetPointer

libs/datasets/combined_datasets.py, tests/libs/api_v2_pipeline_test.py, tests/libs/build_api_v2_test.py, tests/libs/datasets/combined_dataset_utils_test.py, tests/pyseir/icu/infer_icu_test.py, tests/test_helpers.py
This PR follows up on https://github.com/covid-projections/covid-data-model/pull/1066#discussion_r608100854
=> move load_test_dataset from combined_datasets to test_helpers

libs/datasets/combined_datasets.py
=> split CDCVaccinesDataset into states and counties data

api/docs/docs/about.mdx, api/docs/docs/updates.md, api/docs/open_api_schema.json, api/update_open_api_spec.py
This includes US data in documentation
=> add us data to docs

libs/datasets/vaccine_backfills.py
A little refactor to help with https://trello.com/c/tNlZtGp6/1279-make-our-vaccine-backfill-code-smarter
=> use replace_timeseries_wide_dates in vaccine_backfills

data/region-overrides.json
Fix for https://github.com/covid-projections/covid-data-model/commit/e70bb895d896531a4f5b9a198961e09b8af06292
=> rm extra commas in region-overrides.json

libs/datasets/custom_aggregations.py
Noticed this warning while doing a data update locally.
=> Add expected USA columns in unaggregated data.

libs/datasets/vaccine_backfills.py
This PR addresses https://trello.com/c/jeoMFnbb/1243-revisit-backfillvaccinationinitiated-code-1st-dose-2nd-dose-total-doses-in-the-case-of-jj
`backfill_vaccination_initiated` is no longer called.
=> rm backfill_vaccination_initiated

tests/libs/datasets/data_source_test.py, tests/test_helpers.py
Upgrading pandas introduced `TypeError: asdict() should be called on dataclass instances` as documented at https://github.com/pandas-dev/pandas/issues/41682
This PR is a work-around and maybe makes build_dataset slightly easier to read.
=> work-around for asdict error in build_dataset

libs/metrics/icu_headroom.py, libs/metrics/top_level_metrics.py, tests/libs/metrics/icu_headroom_test.py, tests/libs/metrics/top_level_metric_risk_levels_test.py, tests/libs/metrics/top_level_metrics_test.py
Reverts covid-projections/covid-data-model#1131
=> Revert "crudely replace icu metrics with None and np.nan"

api/data_overview_builder.py, api/docs/docs/data-definitions.md, api/docs/open_api_schema.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Annotations.json, api/schemas_v2/AnomalyAnnotation.json, api/schemas_v2/FieldAnnotations.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json
This is definitely hacky, but should get the job done
=> Fix vaxx demographics docs

libs/datasets/combined_datasets.py
=> CDC2 County Data: add filter for counties with 99.9% 12+ init

api/docs/docs/updates.md, libs/metrics/cdc_transmission_levels.py, tests/libs/metrics/cdc_transmission_level_test.py
Moves down the priority of an unknown value. If one of the values is low, it will prefer that over unknown values.
Also improves product update docs to give some more specifics
=> Update definition to lower priority of unknown + update docs

api/can_api_v2_definition.py, api/docs/docs/updates.md
Clarify that we're not regurgitating the CDC level but instead calculating it
with our own data sources, etc.
=> Update CDC Transmission Level docs to be clear about differences.

libs/datasets/combined_datasets.py
This reverts commit 9e3a233bc103b2a435c33d9c2c4e10ca20353fbe.
I accidentally pushed a commit to main -- this reverts it
=> Revert "merged main and remove filters"

.github/workflows/python_unit_tests.yml
mirrors the changes made in https://github.com/rewiringamerica/build-back-electric/pull/174/files
=> Switch to official psf/black@stable github action

libs/parallel_utils.py
=> Reduce number of maximum processes from 64 to 32

.github/workflows/deploy_api.yml, .github/workflows/update_repo_datasets.yml
Made necessary by the swapping of self-hosted runners
=> Update setup-python@v1 to setup-python@v2 on self-hosted actions

scripts/can_raw_location_page_urls.py
=> Fix datapublic imports for location page script 

libs/datasets/combined_datasets.py
Updating CDC Vaccine blocks as the result of the review here: https://www.dropbox.com/scl/fi/rtbyfq9pfvnj2w1fki8fg/02_02_2022_-CDC-Vaccine-data-review.paper?dl=0&rlkey=pq42hko1hxcx6l9ga86bb6f2t
=> Update CDC Vaccine Exclusions

api/can_api_v2_definition.py, api/docs/open_api_schema.json, api/schemas_v2/AggregateFlattenedTimeseries.json, api/schemas_v2/AggregateRegionSummary.json, api/schemas_v2/AggregateRegionSummaryWithTimeseries.json, api/schemas_v2/Annotations.json, api/schemas_v2/Metrics.json, api/schemas_v2/MetricsTimeseriesRow.json, api/schemas_v2/RegionSummary.json, api/schemas_v2/RegionSummaryWithTimeseries.json, api/schemas_v2/RegionTimeseriesRowWithHeader.json, libs/build_api_v2.py, libs/metrics/top_level_metrics.py, libs/pipelines/csv_column_ordering.py, tests/libs/api_v2_pipeline_test.py, tests/libs/build_api_v2_test.py, tests/libs/metrics/top_level_metrics_test.py
This PR addresses issue https://trello.com/c/mQAfsaWF/399-add-cdc-community-level-related-metrics-to-api
=> Implement weeklyCaseDensity

README.md, SETUP.md, cli/data.py
Updates README.md and SETUP.md to remove outdated information and include better instructions for running (parts of) the pipeline locally.  It's not perfect, but hopefully it's a step in the right direction.
=> Update README docs.

.github/workflows/python_unit_tests.yml
Also stops checking out `covid-data-public`.
=> Rework black formatting check in github action.

libs/datasets/statistical_areas.py
=> Revert accidental push

datapublic/common_fields.py, libs/datasets/sources/ca_testing_dataset.py, libs/datasets/sources/state_provided_testing_dataset.py, libs/metrics/test_positivity.py
Tested locally with output: https://gist.github.com/smcclure17/d38268cf5ad6eb054b43508e64705a95
=> Add state testing source to pull in CA data

.github/workflows/CI_test_deploy_api.yml, .github/workflows/deploy_api.yml, .github/workflows/label_api_snapshot.yml, .github/workflows/python_unit_tests.yml, .github/workflows/update_api_usage.yml, .github/workflows/update_repo_datasets.yml, api/can_api_v2_definition.py, api/docs/docusaurus.config.js, datapublic/common_fields.py, libs/datasets/sources/can_scraper_helpers.py, libs/datasets/sources/hsa_population.py, libs/datasets/tail_filter.py, libs/github_utils.py, libs/metrics/top_level_metrics.py, libs/pipeline.py, libs/series_utils.py, scripts/can_raw_location_page_urls.py, services/data-pipeline-dashboard/nginx.conf, tools/build-snapshot.sh, tools/ci-test-publish-api.sh, tools/deploy-docs.sh, tools/label-api.sh, tools/maybe-trigger-web-snapshot-update.sh, tools/trigger-update-datasets.sh
Most of these updates are non-breaking (GitHub would redirect for us), but the GitHub action "checkout repo" action needed to be updated
=> Update organization name

api/docs/docs/updates.md
Open to suggestions/edits to copy. This has no related eng/copy changes, so I think we can ship when ready
=> Add demographic data API doc update
